### ISSUE TITLE
Unpackerr not working and I have no clue why

### ISSUE THREAD

**Issue by g0r3** [Unpackerr/unpackerr#186]
I just noticed that unpacker is not unpacking a download consisting of a *.rar file and *.r00 to *.r9x files. Unfortunately the log gives me no clue why that is the case. Unpacking the file manually works. A search for the error would be greatly appreciated

```
Mar 29 17:10:12 servarr systemd[1]: Started unpackerr - Extracts downloads so Radarr, Sonarr, Lidarr or Readarr may import them..
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.409459 start.go:128: Unpackerr v0.9.9 Starting! (PID: 1000) 2022-03-29 17:10:12.408865905 +0000 UTC m=+0.000428614
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413153 logs.go:210: ==> GoLift Discord: https://golift.io/discord <==
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413174 logs.go:211: ==> Startup Settings <==
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413206 sonarr.go:81:  => Sonarr Config: 1 server: http://127.0.0.1:8989, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/media/torrent"]
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413230 radarr.go:82:  => Radarr Config: 1 server: http://127.0.0.1:7878, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/media/torrent"]
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413239 lidarr.go:87:  => Lidarr Config: 0 servers
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413246 readarr.go:87:  => Readarr Config: 0 servers
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413252 folder.go:74:  => Folder Config: 0 paths, event buffer: 20000
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413259 logs.go:217:  => Using Config File: /etc/unpackerr/unpackerr.conf
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413265 logs.go:218:  => Parallel: 1
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413273 logs.go:219:  => Interval: 2m0s
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413279 logs.go:220:  => Start Delay: 1m0s
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413285 logs.go:221:  => Retry Delay: 5m0s, max: 3
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413291 logs.go:222:  => Debug / Quiet: true / false
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413297 logs.go:225:  => Directory & File Modes: 0755 & 0644
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413304 webhook.go:221:  => Webhook Configs: 0 URLs
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.413310 cmdhook.go:124:  => Command Hook Configs: 0 cmds
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.415888 radarr.go:117: [Radarr] Updated (http://127.0.0.1:7878): 1 Items Queued
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.418648 sonarr.go:116: [Sonarr] Updated (http://127.0.0.1:8989): 0 Items Queued
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.418689 handlers.go:75: [Radarr] Waiting for Start Delay: Super.Legal.Family.Movie.Backup.2021.2160p.UHD.BluRay.x265-g0r3 (1m0s remains)
Mar 29 17:10:12 servarr unpackerr[1000]: 2022/03/29 17:10:12.418698 radarr.go:151: [DEBUG] Radarr: (http://127.0.0.1:7878): completed (torrent:100%): Super.Legal.Family.Movie.Backup.2021.2160p.UHD.BluRay.x265-g0r3
Mar 29 17:11:12 servarr unpackerr[1000]: 2022/03/29 17:11:12.418139 logs.go:143: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
Mar 29 17:11:12 servarr unpackerr[1000]: 2022/03/29 17:11:12.418201 logs.go:145: [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.417656 radarr.go:117: [Radarr] Updated (http://127.0.0.1:7878): 1 Items Queued
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.420532 sonarr.go:116: [Sonarr] Updated (http://127.0.0.1:8989): 0 Items Queued
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.420582 handlers.go:84: [Radarr] Completed item still waiting: Super.Legal.Family.Movie.Backup.2021.2160p.UHD.BluRay.x265-g0r3, no extractable files found at: /media/torrent/Super.Legal.Family.Movie.Backup.2021.2160p.UHD.BluRay.x265-g0r3 (stat err: <nil>)
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.420596 radarr.go:151: [DEBUG] Radarr: (http://127.0.0.1:7878): completed (torrent:100%): Super.Legal.Family.Movie.Backup.2021.2160p.UHD.BluRay.x265-g0r3
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.420606 handlers.go:59: [DEBUG] Radarr: Status: Super.Legal.Family.Movie.Backup.2021.2160p.UHD.BluRay.x265-g0r3 (Waiting, pre-Queue, elapsed: 2m0s)
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.420614 logs.go:143: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
Mar 29 17:12:12 servarr unpackerr[1000]: 2022/03/29 17:12:12.420620 logs.go:145: [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
Mar 29 17:13:12 servarr unpackerr[1000]: 2022/03/29 17:13:12.415019 logs.go:143: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
Mar 29 17:13:12 servarr unpackerr[1000]: 2022/03/29 17:13:12.415081 logs.go:145: [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
```

**Comment by davidnewhall** [comment]
What files are you expecting it to extract?

**Comment by g0r3** [comment]
Not sure if I understand the question. It is a split RAR archive and unpacker seems to not recognize as extractable.

**Comment by davidnewhall** [comment]
(1) Where is this archive located? (2) What are the file names? (3) Why do you think unpackerr doesn't recognize it? (4) What application downloaded the files? (5) Does your starr app show any errors? Please tell me more about the problem, it's not clear what we need to fix. (6) Do other downloads extract OK? (7) Has this ever worked before?

**Comment by g0r3** [comment]
* The files are located in the `/media/torrent/Name.Of.The.Torrent.2021.2160p.UHD.BluRay.x265-RELEASEGROUP` directory
* The files are name in the manner: `Name.Of.The.Torrent.2021.2160p.UHD.BluRay.x265-RELEASEGROUP.rar`  Next to this file, there are many `Name.Of.The.Torrent.2021.2160p.UHD.BluRay.x265-RELEASEGROUP.rXX` files, where `XX` is a running number counting up
* It was downloaded by rTorrent, requested by Radarr
* No, no errors in the *arr App. It only seems to wait for an importable file to appear. The problem is, that unpacker claims as shown above, that `no extractable files found at:` target directory. This target is pointing to the proper directory and this directory contains exrtractable files
* The file is extractable using a archiver. So it is not a damaged file or anything
* This is the first time i experiencing the problem. The first time I installed unpacker, due to having downloaded a compressed torrent, it worked and it unpacked it. Afterwards I never noticed any problems ever again. That could be due to never having downloaded any compressed torrents ever again or - more likely - that it just worked. I never had any reason to check, because everything worked as expected.

**Comment by davidnewhall** [comment]
Please share your docker configuration for unpackerr and radarr. Sounds like a path is set wrong somewhere.

**Comment by davidnewhall** [comment]
Seems very strange. I'm not sure what to say honestly. If there's a rar file in the folder it should find it.

**Comment by davidnewhall** [comment]
This is a permissions issue. The user unpackerr runs as does not have access to the files it needs to extract. Please show me the output of these two commands:
```
ls -ld /media/torrent/{,Name.Of.The.Torrent.2021.2160p.UHD.BluRay.x265-RELEASEGROUP{,/*.rar}}
ps aux | grep unpackerr
```

**Comment by davidnewhall** [comment]
We can fix this...

**Comment by g0r3** [comment]
Hi,
I moved to a seedbox in the meantime, with my Sonarr and Radarr instances running locally. Therefore I am not running unpackerr anymore because unpacking remotely on the sshfs would not be a good Idea. Also I don't have the specific download anymore. But thanks alot for your commitment trying to fix it.

**Comment by JimmyBringus** [comment]
> This is a permissions issue. The user unpackerr runs as does not have access to the files it needs to extract. Please show me the output of these two commands:
> 
> ```
> ls -ld /media/torrent/{,Name.Of.The.Torrent.2021.2160p.UHD.BluRay.x265-RELEASEGROUP{,/*.rar}}
> ps aux | grep unpackerr
> ```

Hello, I am having the exact same issue as well. Here is the output of these commands:

>ls -ld /media/torrent/{,Name.Of.The.Torrent.2021.2160p.UHD.BluRay.x265-RELEASEGROUP{,/*.rar}}

`drwxrwxrwx 1 root root 0 Mar  6 10:08  /mnt/hdd/data/downloads/usenet/complete/movies/`

>ps aux | grep unpackerr

```
pi        980241  0.0  0.0 1240856 16552 ?       Ssl  10:16   0:00 /unpackerr
pi       1040399  0.0  0.0   9212  2688 pts/6    S+   11:50   0:00 grep --color=auto unpackerr
```

**Comment by JimmyBringus** [comment]
A simple “hey open a new ticket” would’ve surely sufficed.

Came here fresh from a google search with no idea the SOPs

**Comment by davidnewhall** [comment]
Welcome to GitHub!

**Comment by JimmyBringus** [comment]
![IMG_1011](https://github.com/Unpackerr/unpackerr/assets/8877150/ed84f02a-065d-49bc-bf76-bc3d49746366)
