### ISSUE TITLE
Question regarding starr app config paths

### ISSUE THREAD

**Issue by varunpan** [Unpackerr/unpackerr#219]
First of all thank you for creating this and keeping some really detail documentation.

I set up my unpackerr using docker-compose example you provided and just had a questions on the path that need to be defined since i have my starr apps running in docker as well. 

Are they path suppose to be the location on the drive or the path as per docker container. for example:
drive path: /mnt/share/downloads
starr app container path: /downloads

Can you clarify which one should be used for the following config parameters?

- UN_SONARR_0_PATHS_0
- UN_RADARR_0_PATHS_0
- UN_LIDARR_0_PATHS_0
- UN_READARR_0_PATHS_0

**Comment by bakerboy448** [comment]
> List of paths where content is downloaded for Readarr

The path unpacker will use to access readarr's downloads

Also if you have /downloads then you have poor paths that result in double space for all torrents and slow IO intensive imports.
https://wiki.servarr.com/docker-guide

**Comment by davidnewhall** [comment]
> Can you clarify which one should be used for the following config parameters?
UN_SONARR_0_PATHS_0
UN_RADARR_0_PATHS_0
UN_LIDARR_0_PATHS_0
UN_READARR_0_PATHS_0

These variables are read by the application in the container. The container has no knowledge of your host or the host paths. These paths are relative to the container, and would generally be set to `/downloads` (the application default).
