### ISSUE TITLE
[Feature Request] Ignore files created before certain date / ignore all existing files

### ISSUE THREAD

**Issue by ryant26** [Unpackerr/unpackerr#249]
Hello, 

Just setup unpackerr for the first time. I already had a solution in place that was extracting archives. Now on first startup unpackerr is going through all those archives and extracting them again. would be ideal if there was some flag to ignore files before a certain date or alternatively to ignore everything that already exists in the *arrs and only extract newly added content. 

Would open a PR myself but I don't know GO. If you can't find the time for this perhaps I'll learn just enough for this :p

**Comment by davidnewhall** [comment]
I don't really understand the problem you're trying to solve. You suggested a solution, but what's wrong?

**Comment by davidnewhall** [comment]
Unpackerr only extracts items that are in your Starr app queues. If you see it extracting things that you do not see in queue, it probably means you have items hiding in your queue.  If that's the case, check out the faq for a way to see those items. https://github.com/davidnewhall/unpackerr/wiki/FAQ

**Comment by davidnewhall** [comment]
If you still need more assistance getting this app to not extract old items, let me know. There's definitely a solution for you here.

**Comment by davidnewhall** [comment]
Please let me know if you got this working.
