### ISSUE TITLE
Unraid Container not unpacking Radarr files

### ISSUE THREAD

**Issue by brixazure** [Unpackerr/unpackerr#262]
as the title says. I am using unpackerr in unraid, and i have movie files it is not unpacking and setting up for radarr to import. Sonarr seems to be functional, radarr is not. This was working a month or so ago but has since stopped. I have reinstalled and checked all radarr related settings. it feels like radarr isnt telling unpackerr there is a file there to unzip or something..

**Comment by davidnewhall** [comment]
Please share the logs.

**Comment by brixazure** [comment]
thought they attached did.. but i cant seem to pull them off unraid.. something about perms..i shall look into that and resolve!

**Comment by brixazure** [comment]
I know there are many,,, but i just want to make sure the info is there. Here are the logs!
[unpackerr.log](https://github.com/Unpackerr/unpackerr/files/10678359/unpackerr.log)
[unpackerr-2023-01-29T04-33-50.503.log](https://github.com/Unpackerr/unpackerr/files/10678355/unpackerr-2023-01-29T04-33-50.503.log)
[unpackerr-2023-01-30T17-54-00.197.log](https://github.com/Unpackerr/unpackerr/files/10678356/unpackerr-2023-01-30T17-54-00.197.log)
[unpackerr-2023-02-02T15-38-49.140.log](https://github.com/Unpackerr/unpackerr/files/10678357/unpackerr-2023-02-02T15-38-49.140.log)
[unpackerr-2023-02-06T18-44-33.236.log](https://github.com/Unpackerr/unpackerr/files/10678358/unpackerr-2023-02-06T18-44-33.236.log)

**Comment by davidnewhall** [comment]
thanks. Which files are you expecting it to unpack?

**Comment by brixazure** [comment]
It was supposed to unpack M3ghan when it downloaded.. it did not.

**Comment by davidnewhall** [comment]
`M3ghan` is not a file. I do not see the string `M3ghan` in any log file you provided.

**Comment by davidnewhall** [comment]
Go into unraid -> Docker, select advanced, then expand the volumes for Unpackerr and Sonarr. Send me a screenshot of each, so I can see the mounted volumes.

**Comment by brixazure** [comment]
hmm.. why didnt it register then from radarr...  image from sonarr and windows share.  also the requested snip. sonarr in there to in case i need to edit that one also. 
![image](https://user-images.githubusercontent.com/38088897/217345858-cb4352a4-0443-44c0-a47b-71a6ceddfd22.png)
![image](https://user-images.githubusercontent.com/38088897/217345957-25a3f41e-be12-445f-ae1d-d0a9d343eb16.png)
![image](https://user-images.githubusercontent.com/38088897/217346273-f55833bb-67cf-491e-a9c3-dfa238d2d5f0.png)

**Comment by davidnewhall** [comment]
Is M3gan still showing in the Radarr queue?

**Comment by brixazure** [comment]
It actually doesnt show in the que even though it shows downloaded both in qbit and radarr.. hm

![image](https://user-images.githubusercontent.com/38088897/217348004-eb8b8308-a082-4b2a-9988-9bee52c09bea.png)

**Comment by davidnewhall** [comment]
That's weird. Radarr acting odd. Again, I never saw it show up in the unpackerr logs, and you included logs from 1/31, so Radarr never "had" this download.... Check to make sure it has the appropriate label/tag/category in qbit.

**Comment by brixazure** [comment]
yupp it shows in the qbit categories,  and in the radarr save path in downloads.

**Comment by davidnewhall** [comment]
I'm not a radarr expert, but what I know is that radarr will only shows files that have the correct category. If it's correct, then you should reach out Radarr devs for support figuring out why it's not showing your download(s). 

If you have any other packed downloads showing in radarr or sonarr queue.. I can help with that. Got any?

**Comment by brixazure** [comment]
Pokémon The Movie: Secrets of the Jungle downloaded but never unpacked. though i dont have logs for it. since it downloaded bk in dec.

**Comment by brixazure** [comment]
that is in sonarr btw.

**Comment by davidnewhall** [comment]
Is it still showing in sonarr queue?

**Comment by brixazure** [comment]
yupp. and i see the folder and zip files in the correct cat and folder patch for downloads.
![image](https://user-images.githubusercontent.com/38088897/217350812-3b651828-7107-4e5f-8749-18d3884cb27e.png)

**Comment by davidnewhall** [comment]
Okay I see that one in your logs. This may be a bug in unpackerr. Give me a few to analyze.

**Comment by bakerboy448** [comment]
All of those series that are greyed out are not parsed/matched to any series in Sonarr and will never auto import - even if unpackerr unpacks them.

that's maybe a factor

**Comment by bakerboy448** [comment]
> It actually doesnt show in the que even though it shows downloaded both in qbit and radarr.. hm
> 
> ![image](https://user-images.githubusercontent.com/38088897/217348004-eb8b8308-a082-4b2a-9988-9bee52c09bea.png)

Radarr has never imported anything for this movie. That screenshot shows a grab only.

either it is no longer in radarr's category in the client,  it can't be parsed and activity => option => show unknown is disabled, or the user has previously told radarr to ignore that release in the client

**Comment by davidnewhall** [comment]
I pushed a test build. Change your docker tag to `golift/unpackerr:unstable` and let me know if that works out any better.

**Comment by brixazure** [comment]
> > It actually doesnt show in the que even though it shows downloaded both in qbit and radarr.. hm
> > ![image](https://user-images.githubusercontent.com/38088897/217348004-eb8b8308-a082-4b2a-9988-9bee52c09bea.png)
> 
> Radarr has never imported anything for this movie. That screenshot shows a grab only.
> 
> either it is no longer in radarr's category in the client, it can't be parsed and activity => option => show unknown is disabled, or the user has previously told radarr to ignore that release in the client
> 
> if the file for that release is in radarr and shows under files - then you're downloading to your root folder or have another application moving downloads to your library folder. Neither are supported and cause all sorts of weird issues.

downloads is just for sonar, radarr, and they are supposed to move their respective files themselves once they show downloaded. and it is in the radarr cat in qbit. and Show unknown movie items is checked

**Comment by brixazure** [comment]
updated and adding a new movie that i confirmed has zip files to radarr

**Comment by brixazure** [comment]
looks like it might be an issue with radarr then since it doesnt show in the que in the logs. hmm.

**Comment by davidnewhall** [comment]
Have any luck figuring this out?

**Comment by brixazure** [comment]
actually solved last night, after trying a brand new instance of unpackerr.. talked to some people int he err disocrd and was able to resolve. turns out my DB was corrupted baddly.. redid the DB and it works now. :D  this can be closed. :D
