### ISSUE TITLE
Permission issues with output (Docker)

### ISSUE THREAD

**Issue by Jdiesel87** [Unpackerr/unpackerr#263]
I've been having issues with the permissions of extracted files 

Input:
-rw-rw-rw- 1 nobody users   50000000 Feb  2 15:49 *****.rar

Output:
-rw-r--r-- 2 root   root  2488811602 Feb  2 15:55 *****.mkv

I am using Unraid and have tried adding variables for UMASK 000, PUID 99, and PGID 100 but they seem to be ignored

> 2023/02/02 15:57:33 Unpackerr v0.11.1 Starting! PID: 1, UID: 0, GID: 0, Now: 2023-02-02 15:57:33 -0600 CST
2023/02/02 15:57:33 Missing Lidarr URL in one of your configurations, skipped and ignored.
2023/02/02 15:57:33 ==> GoLift Discord: https://golift.io/discord <==
2023/02/02 15:57:33 ==> Startup Settings <==
2023/02/02 15:57:33  => Sonarr Config: 1 server: http://192.168.1.233:8989, apikey:true, timeout:15s, verify ssl:false, protos:torrent, syncthing: false, delete_orig: false, delete_delay: 5m0s, paths:["/Storage/torrents/tv"]
2023/02/02 15:57:33  => Radarr Config: 1 server: http://192.168.1.233:7878, apikey:true, timeout:15s, verify ssl:false, protos:torrent, syncthing: false, delete_orig: false, delete_delay: 5m0s, paths:["/Storage/torrents/movies"]
2023/02/02 15:57:33  => Lidarr Config: 0 servers
2023/02/02 15:57:33  => Readarr Config: 0 servers
2023/02/02 15:57:33  => Folder Config: 0 paths, event buffer: 20000
2023/02/02 15:57:33  => Using env variables only. Config file not found.
2023/02/02 15:57:33  => Parallel: 1
2023/02/02 15:57:33  => Passwords: 0 (rar/7z)
2023/02/02 15:57:33  => Interval: 2m
2023/02/02 15:57:33  => Start Delay: 1m
2023/02/02 15:57:33  => Retry Delay: 5m, max: 3
2023/02/02 15:57:33  => Debug / Quiet: false / false
2023/02/02 15:57:33  => Activity / Queues: false / 1m
2023/02/02 15:57:33  => Directory & File Modes: 755 & 644
2023/02/02 15:57:33  => Log File: /downloads/unpackerr.log (10 @ 10Mb)
2023/02/02 15:57:33  => Webhook Configs: 0 URLs
2023/02/02 15:57:33  => Command Hook Configs: 0 cmds

**Comment by davidnewhall** [comment]
Add `--user 99:100` to the `Post Arguments` on the container in Unraid. You need to toggle advanced to see it.
![Screen Shot 2023-02-02 at 2 51 13 PM](https://user-images.githubusercontent.com/2402929/216469265-4a2a3634-b4d2-4462-86e8-977d0c35523a.png)

**Comment by davidnewhall** [comment]
That work for you?

**Comment by Jdiesel87** [comment]
I switched to a different template and it sorted out my issue.

https://hub.docker.com/r/hotio/unpackerr worked for me out of the box. 

I did try try adding "--user 99:100" to my existing template but it failed to start.

**Comment by davidnewhall** [comment]
It probably failed to start because the log file was owned by root and it couldn't write to it. hotio container supports PUID and PGID, so that's a good workaround.
