### ISSUE TITLE
Lost with Unraid Mapping 

### ISSUE THREAD

**Issue by soldius** [Unpackerr/unpackerr#265]
Could you please help me with the unraid mapping? I have tried almost all the combinations and still can't figure it out. I even tried to use one of the solved issue and still couldn't map it right. Below are my config:

![image](https://user-images.githubusercontent.com/44028743/218524395-52404af0-cda5-45ae-bc8a-d83bf1885488.png)
![image](https://user-images.githubusercontent.com/44028743/218524144-52317784-366e-4df8-8fe4-2e5b81a45496.png)
![image](https://user-images.githubusercontent.com/44028743/218524175-26ae285f-f822-4111-8201-0a68ac55d9d9.png)

Also... I couldn't figure out how to get the docker to install to my /mnt/user/appdata folder. I even tried to create a path for the /config to map to /mnt/user/appdata/unpackarr but the folder is just empty.

Thank you!

**Comment by davidnewhall** [comment]
The four log lines you pasted make it look like it's working. What are you expecting it to extract?

**Comment by soldius** [comment]
Oh, it is correct? It keeps saying no such file or directory so I assumed it is still not working properly.

**Comment by davidnewhall** [comment]
Well your paths are set incorrectly. Looks like you set them to `/` but they should be inside `/data`. Possibly `/data/downloads`. So you keep getting an error for that, but then right after that it seems to find the download. Then it says it has no extractable files. Seems like it's working, but you could fix the paths to get fewer errors in debug.

**Comment by davidnewhall** [comment]
> I couldn't figure out how to get the docker to install to my /mnt/user/appdata folder.

The app runs fine without an appdata folder. Adding one allows you to use [a config file](https://github.com/Unpackerr/unpackerr/blob/main/examples/unpackerr.conf.example), but it's not required. 

You should also set your log file to `/data/unpackerr.log` .. just noticed that typo too.

**Comment by soldius** [comment]
I just made the changes you mentioned. Is there a way to tell if it is extracting correctly? Thank you so much for helping me with the config!

**Comment by davidnewhall** [comment]
> Is there a way to tell if it is extracting correctly?

Give it something to extract.

**Comment by soldius** [comment]
Ok. I will download something and watch its behavior. Thank you!!

**Comment by soldius** [comment]
I set the Sonarr and Radarr to /data like you suggested and it is working!

`2023/02/13 13:32:56.442236 handlers.go:73: [DEBUG] Sonarr: Status: VINLAND.SAGA.S02E03.1080p.WEB.H264-SENPAI (Extracted, Awaiting Import, elapsed: 1h36m23s)
2023/02/13 13:32:56.442308 handlers.go:73: [DEBUG] Sonarr: Status: VINLAND.SAGA.S02E05.1080p.WEB.H264-SENPAI (Extracted, Awaiting Import, elapsed: 1h37m47s)
2023/02/13 13:32:56.442386 handlers.go:73: [DEBU`

**Comment by davidnewhall** [comment]
Why isn't Sonarr importing that item? You should see the error in Sonarr Activity Queue.

**Comment by soldius** [comment]
Oh, it is just a "not a preferred word upgrade". So I probably got something similar or better quality :). Thank you so much for your help!! It was super quick and helpful 👍

**Comment by davidnewhall** [comment]
No prob! Glad it's working!
