### ISSUE TITLE
File Filtering

### ISSUE THREAD

**Issue by vra1974** [Unpackerr/unpackerr#266]
Is there a way to tell unpackerr to NOT unpack files with certain files/folders? 
I want to avoid extracting "sample" files and folders.

**Comment by davidnewhall** [comment]
It's going to extract everything in the download that is compressed. No way to adjust that as-is. What problem are you having?

**Comment by vra1974** [comment]
I use it to handle my Sonarr/Radarr 
But some torrents come with sample files and folders. Sonarr and Radarr get crazy when they find one of those.

**Comment by vra1974** [comment]
Well, I am having trouble because Radarr and Sonarr say "Import Rejected: Sample"  when torrent contains sample files or folders.

**Comment by davidnewhall** [comment]
That indicates the download location does not contain an importable non-sample file. The starr apps correctly ignore the sample, but they're not finding the real content. Is it there?

**Comment by austinwbest** [comment]
It can also happen with broken files and bad media info

**Comment by vra1974** [comment]
I see that Unpackerr is unpacking the files in another folder aside the original for some files. It adds a "-1" to the folder name where it extracts the contents.

And there are some torrents that get unpacked on the root folder instead of unpacking all the files on the same folder where the RAR files are. 

What would be the config to fix this?

**Comment by bakerboy448** [comment]
> And there are some torrents that get unpacked on the root folder instead of unpacking all the files on the same folder where the RAR files are.

If it's only some torrents - do you have a script or another application unpacking things?

otherwise your unpackerr config defines where files are unpacked to, but that wouldn't be only applying to _some_ downloads

what's your config look like (redact any credentials)

**Comment by davidnewhall** [comment]
> It adds a "-1" to the folder name where it extracts the contents.

I've never seen this behavior, and I didn't write any code that would do this. 

> And there are some torrents that get unpacked on the root folder instead of unpacking all the files on the same folder where the RAR files are.

Honestly, this sounds like you have some other app or script doing unrar. Unpackerr extracts everything into a folder named `<Original_Folder_Name>_unpackerred`, then it renames the files it extracted back into `<Original_Folder_Name>`.  What you described is something else.

**Comment by vra1974** [comment]
I see! Just checked and it is as you tell me.
Problem is that it is not moving the file to the original folder.
![Screenshot_20230217-082706](https://user-images.githubusercontent.com/125486414/219683588-2c4fa21c-9c95-479e-9ae4-848863d8b0e5.png)
![Screenshot_20230217-082742](https://user-images.githubusercontent.com/125486414/219683754-f189a17c-124b-4564-b9d7-db1a3cd6a42a.png)

**Comment by davidnewhall** [comment]
Share the logs so I can find out why.

**Comment by davidnewhall** [comment]
Do you still need help with this?

**Comment by davidnewhall** [comment]
The log you provided does not match the config file you provided. You've found a bug in the command hooks. I opened this task to track that fix: https://github.com/golift/cnfg/issues/12 - remove the command hook to remove that crash.

**Comment by davidnewhall** [comment]
Did removing the command hook help?
