### ISSUE TITLE
Sonarr Invalid Status Code Error

### ISSUE THREAD

**Issue by SirAtlass** [Unpackerr/unpackerr#268]
I have Unpackerr setup and functioning fine for Radarr, but watching the logs I see constant errors for Sonarr.  The whole setup is built on a Win10 VM machine. The errors read

"[ERROR] Sonarr (http://127.0.0.1:8989/): api.get(v3/queue): invalid status code, 404 >= 300, NotFound"

I'm a little perplexed because the only difference between Sonarr and Radarr is the port and it seems to be running just fine. I've confirmed everything is up to date and the Sonarr API key is correct. Also shutdown and completely restarted both the service, VM and the entire server.

**Comment by bakerboy448** [comment]
Are you still running sonarr v2 which is EOL?

**Comment by SirAtlass** [comment]
Sigh....

Yes.  I incorrectly assumed the "update" would have me on the latest version.  Stupid me.

Thank you for pointing it out!
