### ISSUE TITLE
Bunch of items stuck in "Completed item still waiting"

### ISSUE THREAD

**Issue by kocane** [Unpackerr/unpackerr#270]
I've noticed I have some 12 items (2 of em from Radarr and 10 from Sonarr) that are stuck in "completed item still waiting". Not only are these items ancient, they are also no where to be found in the queues of Sonarr and Radarr. So of course it also reports that "no extractable files found at *path*" 

Where does Unpackerr get it from? Can I make it forget these items? Seemingly it doesnt happen to any newly added items.

**Comment by bakerboy448** [comment]
Unpackerr gets the item from Starr queue

is options => show unknown enabled in starr ?

Can you post your unpackerr logs?

**Comment by bakerboy448** [comment]
https://trash-guides.info/Radarr/Tips/Radarr-show-unknown-movie-items/

**Comment by kocane** [comment]
Right on, thanks man!

**Comment by davidnewhall** [comment]
The process is also documented here: https://github.com/Unpackerr/unpackerr/wiki/FAQ
