### ISSUE TITLE
Unpackrr intermittently fails to delete $movietitle_unpackerred directories

### ISSUE THREAD

**Issue by NSADrone** [Unpackerr/unpackerr#272]
Using Unpackrr on UNRAID 6.11.5 with Hotio's Docker App. And seeing behavior where Unpackrr intermittently fails to delete $movietitle_unpackerred directories. Have not been able to isolate in the logs yet when this is occurring and what the logs are writing when it occurs. 

When it works correctly, I am seeing messages like below. Which speak to it being intermittent.

2023/03/09 12:11:40 Deleted (recursively): /data/torrents/movies/Alpha.2018.1080p.BluRay.x264-DRONES_unpackerred
2023/03/09 12:11:40 Deleted (recursively): /data/torrents/movies/Alpha.2018.1080p.BluRay.x264-DRONES_unpackerred/Subs

When it does not work I am left with several empty directories in the root directory that unpackerr never goes back to clean up.
![image](https://user-images.githubusercontent.com/98303232/224106998-600b8337-7b67-462d-9ebd-490ce5a9a8ad.png)

**Comment by davidnewhall** [comment]
When you have those logs we can definitely investigate.

**Comment by davidnewhall** [comment]
Would still like to get to the bottom of this. Has it happened again?

**Comment by NSADrone** [comment]
It has not recently but it was still happening when I reported it but apologies for not coming back to update this. 

I ended up just excluding downloads in zipped format as the solution for my setup. 

I am currently on several weeks of travel for work but I can take a look at it when I get back home.

**Comment by wacko37** [comment]
Ok I can provide logs for this same issue of the EMPTY "temp" folder that unpackerr creates is not getting deleted and then Sonarr continues to keep items in the queue because of the empty folder.

I'm using the Selfhosters golift/unpackerr docker found in Unraid CA and added the variable; UN_SONARR_0_DELETE_ORIG

Before adding the extra var I was left with both the original files/folder & the empty Unpackerr Temp folder, after applying the var the original folder/files are deleted as expected but still the empty temp folder remains.

Once I manually delete the temp folder, Sonar clears the queued items. 

[unpackerr.log](https://github.com/Unpackerr/unpackerr/files/12272542/unpackerr.log)

**Comment by davidnewhall** [comment]
@wacko37 what folder did you have to delete?

**Comment by davidnewhall** [comment]
I do see something that looks fishy. It also looks like Sonarr is doing something weird, but I'm not sure. This log is interesting for sure.

**Comment by wacko37** [comment]
thanks for the reply @davidnewhall And thanks for all that you do and this great piece of software.

WOW my 1st bit of debug help ever and it actually made some sense....lol! 

As long as unpackerr can delete the parent folder it will clear the queue within sonarr.

Yes I also thought it was weird that sonarr was seeing and empty folder (no sub folders or files) as  something to import, it had all 8 episodes listed in the queue even though the folder in question was empty.

**Comment by davidnewhall** [comment]
@wacko37 Can you grab the unstable version and let me know if it works better? https://unstable.golift.io

**Comment by wacko37** [comment]
> @wacko37 Can you grab the unstable version and let me know if it works better? https://unstable.golift.io

Thanks @davidnewhall for this fix and your continued develeopmment.

Sadly I wont be able to test this for a while as Im away for work also....lol.... just like the original OP, maybe @NSADrone  can help finishing this 1 out. Otherwise I look into it when I return home.

**Comment by davidnewhall** [comment]
No worries. It was a simple and safe change, so I'll probably just get it all merged anyway. I'm pretty sure it'll resolve this particular problem too. Thanks for your response!

**Comment by wacko37** [comment]
Brilliant work, I'll let it update on the stable release then so, and monitor logs/folders.

I know where to report if anything unusual happens.

No mate, thank you for all that you do! people are to quick to forget the time others put into making applications like this a possibility. And then share it for free for others to enjoy.
