### ISSUE TITLE
Don't understand how to set up folder/mounting

### ISSUE THREAD

**Issue by Schaka** [Unpackerr/unpackerr#281]
I'm using UnRAID and don't understand how to set up the folder/mounting structure.

My folder structure is as follows:

```
- /mnt/user/share_media/
    - torrents
        - tv
        - movies
    - media
        - tv
        - movies
```

The `media` folder contains as media after a successful download. `torrents` folder contains complete downloads, because they're seeding and/or are unpackable archives. Normally these would be hard linked to their respective place in the media folder by sonarr/radarr and I could theoretically seed them forever if I wanted to. 

Setting the downloads location to `/mnt/user/share_media/`and sonarr download folder to `/mnt/user/share_media/torrents/tv` does nothing. I've tried different combinations, I've tried not using absolute paths for the sonarr download folder and I've tried linking to `media/tv` instead. 

I can't seem to figure out what the expected behavior is. Should I be pointing towards the imported collection or the un-imported downloads (the ones which sonarr/radarr can't import, because they're rar files)?

**Comment by davidnewhall** [comment]
Simply mount the same downloads path on Unpackerr that you mount on Sonarr.  Sonarr tells Unpackerr where the files are, so if you put them in the same path it should just work.

**Comment by Schaka** [comment]
Seems to have worked.
Setting both container's download folders to `/mnt/user/share_media/`, everything works.
Individual paths were moved to `media/movies` and `media/tv`. Can't say whether this was necessary though.
