### ISSUE TITLE
Option for No Delete Delay

### ISSUE THREAD

**Issue by Foehammer1982** [Unpackerr/unpackerr#288]
Hey could you possibly give an option in the template for no delete delay?

This is really helpful to us who hardlink/symlink their content. If unpackerr is deleting the extracted file then it removes the hardlink and this is quite annoying as this docker does not create a config file or folder in unRAID's app data folder that we can change. This variable is available in other unpackerr dockers to set but yours is the easiest to setup path wise. 

I was able to force this through editing the docker xml template i changed 1m to -1s for the "delete delay" variable. Deleted the container and then hit add container and pulled it back down using the editted template. 

For note as well, unpacker will still claimed to have deleted the file but the hardlink count does remain the same. As long as unpackerr logs read -1s for its delete delay when it starts, then it has taken the variable

**Comment by davidnewhall** [comment]
> Hey could you possibly give an option in the template for no delete delay?

I'll consider it, but ....  The problem you're describing is unique and sounds like normal behavior that's confusing you. Most folks want extracted files deleted, and I believe you do too.

> If unpackerr is deleting the extracted file then it removes the hardlink

That's not how file system links work. If a file inode has 2 links, and unpackerr deletes one link, it will then have 1 link remaining. **What behavior are you having?**

> this docker does not create a config file or folder in unRAID's app data folder that we can change

Unpackerr? You can mount an appdata folder at `/config` and give it a config file at `/config/unpackerr.conf`. That's [explained in the readme](https://github.com/Unpackerr/unpackerr#docker-config-file).

> I was able to force this through editing the docker xml template i changed 1m to -1s for the "delete delay" variable.

You can turn on advanced view in the unraid UI to add `-1s`. No editing XML required.
![Screenshot 2023-05-07 at 11 23 51 PM](https://user-images.githubusercontent.com/2402929/236749779-d7a51a57-e626-4e5b-b29d-d09dc5fd72d2.png)

![Screenshot 2023-05-07 at 11 23 42 PM](https://user-images.githubusercontent.com/2402929/236749773-679e16ba-eff0-4730-9cb8-b056e9088141.png)

> unpacker will still claimed to have deleted the file

It doesn't actually claim this. It just sets the status to deleted and leaves the extracted file in the download location. Nothing is deleted when delete delay is less than 0.

> but the hardlink count does remain the same

Of course. When nothing is deleted, the inode will still have 2 links. The one in your media location, and the one in your download location. You no longer need the one in the download location, **but I think you think you do.** You don't, and you should put delete delay back to `1m`.
