### ISSUE TITLE
Configure poll interval for folder watching

### ISSUE THREAD

**Issue by jimmycuadra** [Unpackerr/unpackerr#289]
Hi, I noticed that the folder watching functionality polls the disk every second for files to extract. Is there a way to configure this interval? I don't need it to be that quick to react and would rather reduce the wear and tear on my disk. Thanks!

**Comment by davidnewhall** [comment]
```toml
[folders]
interval = "10s"
```
or `UN_FOLDERS_INTERVAL=10s`

**Comment by davidnewhall** [comment]
If you want even less IO, don't run it in Docker and it won't start the file system poller.

**Comment by davidnewhall** [comment]
I'm glad those settings worked for you. So few people need them that I've chosen not to document them. They are advanced settings that generally should not need changing. In cases where changing them is needed, I like to understand why, by having this short conversation. The really advanced users tend to find [them](https://github.com/Unpackerr/unpackerr/blob/main/pkg/unpackerr/apps.go#L75-L76) on their own. 

Let me know if I can help with any other tuning!
