### ISSUE TITLE
Unpacked files permission is set to -rwxr-xr-x. Can't change.

### ISSUE THREAD

**Issue by Grenwalls** [Unpackerr/unpackerr#292]
Heyo, I had an issue with it setting to root as well, but that was solved with --user="99:100".
However my post processing stuff still can't access the files, because the permissions are set to -rwxr-xr-x.
I've tried some stuff to make unpackerr change it, like UN_FILE_MODE and UN_DIR_MODE as well as trying extra parameters, but nothing seems to work. 

How can I make the output files be unmasked 0000 or -rwxrwxrwx?

**Comment by bakerboy448** [comment]
- UN_FILE_MODE=0644
- UN_DIR_MODE=0755

as env vars should do it?

**Comment by bakerboy448** [comment]
Golift container unpacker logs from startup and the compose?

**Comment by davidnewhall** [comment]
Have you tried setting `UMASK`?

**Comment by davidnewhall** [comment]
@Grenwalls You still experiencing an issue here and need assistance? This could very well be related to a recent change. With your help we can narrow it dow and resolve it. Let me know?

**Comment by davidnewhall** [comment]
> I changed to the hotio version and got it working, it respected the settings.

I actually just saw this. welp.
