### ISSUE TITLE
Not working for radarr

### ISSUE THREAD

**Issue by Buster14** [Unpackerr/unpackerr#311]
I really like this but it doesn't seem to work for my radarr install on windows server
```
[[radarr]]
url = "http://127.0.0.1:7878"
api_key = "7cf9db5038444442a6cead03f7d00869"
## File system path where downloaded Radarr items are located.
## Default protocols is torrents. Alternative: "torrent,usenet"
protocols = "torrent"
## How long to wait for a reply from the backend.
timeout = "10s"
## If you use this app with NZB you may wish to delete archives after extraction.
## General recommendation is: do not enable this for torrent use.
## Setting this to true deletes the entire original download folder after import.
#  delete_orig = false
```
Double checked and the api key is correct, port used is correct too.
I assigned username password but there's no way to input them,  besides my sonarr works w/o username password.
For sonarr it works but sometimes an episode is skipped if there' s alot of episodes at once.

Also another question, for [folders] option, how do i make unpackerr extract to original folder, instead of creating another folder with -unpackerr name after it?

**Comment by davidnewhall** [comment]
> doesn't seem to work for my radarr 

You're going to have to share more about the problem. Logs tell us what unpackerr is doing.

> For sonarr it works but sometimes an episode is skipped

It skips a rar file? Again, need more info, and probably logs.

>  how do i make unpackerr extract to original folder,

You cannot. It always extracts into a temporary folder, and then optionally moves the extracted files back.

**Comment by Buster14** [comment]
I disabled the folder option and it seems to be working again, but sometimes its still missing a movie.
This one just happened last night. I'll post the relevant log parts
```

2023/06/16 16 06:09:08.611857 handlers.go:73: [DEBUG] Radarr: Status: Punch.2022.1080p.WEB.H264-DiMEPiECE (Waiting, pre-Queue, elapsed: 11h32m0s)
16 06:11:08.281025 handlers.go:214: [DEBUG] Radarr: Errors encountered looking for Punch.2022.1080p.WEB.H264-DiMEPiECE path: ["CreateFile C:\\downloads\\Punch.2022.1080p.WEB.H264-DiMEPiECE: The system cannot find the file specified."]

2023/06/16 16 06:11:08.281994 handlers.go:232: [DEBUG] Radarr: Configured paths do not exist; could not find alternative path in error message for Punch.2022.1080p.WEB.H264-DiMEPiECE
2023/06/16 06:11:08.281994 handlers.go:98: [Radarr] Completed item still waiting: Punch.2022.1080p.WEB.H264-DiMEPiECE, no extractable files found at: C:\downloads\Punch.2022.1080p.WEB.H264-DiMEPiECE (stat err: CreateFile C:\downloads\Punch.2022.1080p.WEB.H264-DiMEPiECE: The system cannot find the file specified.)
2023/06/16 06:11:08.281994 radarr.go:152: [DEBUG] Radarr: (http://127.0.0.1:7878): completed (torrent:100%): Punch.2022.1080p.WEB.H264-DiMEPiECE
2023/06/16 06:11:08.699497 handlers.go:73: [DEBUG] Radarr: Status: Punch.2022.1080p.WEB.H264-DiMEPiECE (Waiting, pre-Queue, elapsed: 11h34m0s)
```

**Comment by davidnewhall** [comment]
Can you send the whole log? Need to see the settings that are printed at startup.

**Comment by Buster14** [comment]
https://pastebin.com/FN75gsSf

Like this? My server is 24/7 and fortunately the log file that i used was still open

**Comment by davidnewhall** [comment]
Unfortunately the startup settings are not there. Can you set a log file so unpackerr writes to a file?

The log is full of "file not found" .. what's going on there? Are the files there? show me?

**Comment by Buster14** [comment]
> Unfortunately the startup settings are not there. Can you set a log file so unpackerr writes to a file?
> 
> The log is full of "file not found" .. what's going on there? Are the files there? show me?

How do i do that?
The config is already set to log_file = "/downloads/unpackerr.log"

For the successful ones e.g extracted, the log is correct there's no file to be extracted indeed, so thats probably say why its not found.

But for my "punch (2022) example above (as of now its' still unextracted showing yellow error in radarr)
I think this is the relevant log, I dont understand why does unpackerr need to create file under C\\downloads like this?

2023/06/16 06:11:08.281025 handlers.go:214: [DEBUG] Radarr: Errors encountered looking for Punch.2022.1080p.WEB.H264-DiMEPiECE path: ["CreateFile C:\\downloads\\Punch.2022.1080p.WEB.H264-DiMEPiECE: The system cannot find the file specified."]
Some kind of temp file?

**Comment by davidnewhall** [comment]
> How do i do that?

You did:

> The config is already set to log_file = "/downloads/unpackerr.log"

Send me that file?

> why does unpackerr need to create file under C\downloads like this?

`CreateFile` is just the message Windows provided when unpackerr tried to find the directory. 

Where is Punch.2022? What path? Can you show me?

**Comment by Buster14** [comment]
![punch](https://github.com/Unpackerr/unpackerr/assets/13533437/b6c35fab-b2c5-4d82-b4b9-405e4786991c)
Path seems to work, theres a bunch unpackerr log files with unpackerr_date name.log, this is the unpackerr.log :
[unpackerr.log](https://github.com/Unpackerr/unpackerr/files/11778264/unpackerr.log)

**Comment by davidnewhall** [comment]
Okay, you should be able to fix this by setting the `paths` variable to `['n:\temp']`

ie.
```
[[starr]]
 url = "http://127.0.0.1:0000"
 api_key = "stuff"
 paths = ['n:\temp']
```

Add any other paths where you expect files to be. 

ie. 
```
paths = ['n:\temp', 'c:\other\path', 'n:\temp\complete']
```

**Comment by davidnewhall** [comment]
Also curious.. the log says it's process (extracted and had imported) over 300 items. Have those been radarr items or Sonarr items? or both? It seems like it mostly just works, right?

**Comment by Buster14** [comment]
> Okay, you should be able to fix this by setting the `paths` variable to `['n:\temp']`
> 
> ie.
> 
> ```
> [[starr]]
>  url = "http://127.0.0.1:0000"
>  api_key = "stuff"
>  paths = ['n:\temp']
> ```
> 
> Add any other paths where you expect files to be.
> 
> ie.
> 
> ```
> paths = ['n:\temp', 'c:\other\path', 'n:\temp\complete']
> ```
> 
> Update the config as noted above. Restart unpackerr. Wait ~15 minutes. If it doesn't work, send me the new log file, and a screenshot of Radarr's yellow triangle w/ error message. I need to see if Radarr has the path in the message.

Just the expected path where the .rar would be right?
Ok done, will monitor it.

> Also curious.. the log says it's processed (extracted and had imported) over 300 items. Have those been Radarr items, or Sonarr items, or both? It seems like it mostly just works, right?

Yeah mostly, but sometimes it is still missing some items.

**Comment by davidnewhall** [comment]
> Just the expected path where the .rar would be right?

The path that contains the _folders_ that are downloaded with rar files in them. In your screenshot the folder with rar files is in `n:\temp`, but I see slightly different paths coming from your Starr apps, so I'm just prepping you for adding other folders if that setting doesn't get them all.

**Comment by Buster14** [comment]
> > Just the expected path where the .rar would be right?
> 
> The path that contains the _folders_ that are downloaded with rar files in them. In your screenshot the folder with rar files is in `n:\temp`, but I see slightly different paths coming from your Starr apps, so I'm just prepping you for adding other folders if that setting doesn't get them all.

It works, the items are extracted, thanks, i'll mark it as solved.
Should not missed anything again with this setup right?

**Comment by davidnewhall** [comment]
> Should not missed anything again with this setup right?

Even with the wrong path set, Unpackerr was extracting almost everything. Normally, Starr apps tell Unpackerr where to find the stuff, but sometimes they don't. You noticed. Setting the paths variable gives Unpackerr "somewhere else" to look. If your files get put into other places before import, just add the paths and it should work out. 

I think you're all set now though since that worked! Glad it's been going well for ya!
