### ISSUE TITLE
Unable to unpack files sent to samba share

### ISSUE THREAD

**Issue by Hizakix92** [Unpackerr/unpackerr#316]
OS - Ubuntu 22.04 running under Proxmox 7

Setup 8core 12GB of ram.
Built a samba share on unpackerr 128GB in size.

```
[Downloads]
   comment = Downloads
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   writable = yes
   path = /home/david/downloads
```

Goal - To be able to download zipped files from my Windows system to the download share being hosted by unpackerr to automate the unzipping process.

Issue - After connecting a Windows system to this samba share being hosted by the unpackerr VM I am unable to unzip the files in question. Unpackerr doesn't even see files in the directory.

4.0K drwxrwxrwx 2 david  david 4.0K Jun 19 02:30 downloads

the user david does belong to the root group. 

```
 root@unpackerr:/home/david# sudo systemctl status unpackerr
● unpackerr.service - unpackerr - archive extraction daemon
     Loaded: loaded (/lib/systemd/system/unpackerr.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-06-19 02:42:32 UTC; 1min 45s ago
   Main PID: 19326 (unpackerr)
      Tasks: 10 (limit: 14210)
     Memory: 1.6M
        CPU: 34ms
     CGroup: /system.slice/unpackerr.service
             └─19326 /usr/bin/unpackerr

Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405170 logs.go:221:  => Start Delay: 1m
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405184 logs.go:222:  => Retry Delay: 5m, max: 3
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405198 logs.go:223:  => Debug / Quiet: true / false
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405212 logs.go:224:  => Activity / Queues: false / 1m
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405226 logs.go:227:  => Directory & File Modes: 0777 & 0777
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405246 webhook.go:267:  => Webhook Configs: 0 URLs
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.405274 cmdhook.go:124:  => Command Hook Configs: 0 cmds
Jun 19 02:42:32 unpackerr unpackerr[19326]: 2023/06/19 02:42:32.408225 folder.go:113: [Folder] Watching (fsnotify): /home/david/downloads
Jun 19 02:43:32 unpackerr unpackerr[19326]: 2023/06/19 02:43:32.410107 logs.go:142: [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
Jun 19 02:43:32 unpackerr unpackerr[19326]: 2023/06/19 02:43:32.410212 logs.go:144: [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
```

At the moment I do have one file present in "/home/david/downloads"

Please note, I am only using the " folder " subsection of the configuration file.

```
[[folder]]
path = '/home/david/downloads'
## Path to extract files to. The default (leaving this blank) is the same as `path` (above).
# extract_path = ""
## Delete extracted or original files this long after extraction.
## The default is 0. Set to 0 to disable all deletes. Uncomment it to enable deletes. Uses Go Duration.
#delete_after = "10m"
## Delete extracted files after successful extraction? true/false, no quotes. Honors delete_after.
#delete_files = false
## Delete original items after successful extraction? true/false, no quotes. Honors delete_after.
delete_original = true
## Disable extraction log (unpackerred.txt) file creation? true/false, no quotes.
# disable_log = false
## Move extracted files into original folder? If false, files go into an _unpackerred folder.
# move_back = false
## Set this to true if you want this app to extract ISO files with .iso extension.
# extract_isos = false
```

is this just a limitation of fsnotify?

Thank you for your help!
David.

**Comment by davidnewhall** [comment]
fsnotify doesn't work over CIFS (samba). You can force the poller to start (it starts by default under Docker which also has fsnotify problems). Add this to the bottom of your config file to force the poller.
```
[folder]
interval = "1s"
```

My question though.. why not run unpackerr on windows? It's a lot more efficient when it runs local to the files.

**Comment by davidnewhall** [comment]
It's also questionable if your host system provides fsnotify to your virtual machines. Since they have virtual drives, it's all a virtual mystery.

**Comment by Hizakix92** [comment]
Hi! Thank you so much for getting back so quickly, I really appreciate it.

The reason why this isn't being ran on the host system is purely resource related. This poor laptop needs more storage, however I have an absolute ton of storage available to my hosts and/or  my truenas boxes that I can leverage.  I will give the poller shot an attempt. But I do agree that this will end up being a bit of a virtual mystery. If I can't get anywhere with this I'll revisit unpackerr once I can leverage more storage space. 

For now I'll go ahead and close this out.
Thanks David!

**Comment by Hizakix92** [comment]
Oh! I didn't see your edit prior to my last reply.

The final destination of the files will be brought over to a trueNAS box, I did not want to use this as the target primarily due to the poor CPU performance. I figured it'd be a terrible system to run extractions on. The files pathing would look like this:
Windows laptop-> samba(CIFS) share being hosted on the unpackerr VM -> Extract file  on the CIFS share -> run a cronjob at XYZ time to move the files out of the share to its final resting spot on trueNAS.  

I did make the poller change, however this didn't resolve the concern, I am considering re-attempting the deployment on unpackerr on to an LXC container to see if that fairs any better. However, I do think I am just at the limitations of fsnotify. 

Thanks for you time!

**Comment by davidnewhall** [comment]
Unpackerr will only extract a folder, which generally works well for torrent downloads. It's less useful for browser downloads because they do not create folders. Here's how you can make it work. You have this file `/mnt/storage/Target/Test.zip`... 

Make a folder then move that file into it.  Do this while unpackerr is running.
```
mkdir /mnt/storage/Target/myDL
mv /mnt/storage/Target/Test.zip /mnt/storage/Target/myDL
```

**Comment by davidnewhall** [comment]
> run a cronjob at XYZ time to move the files out of the share to its final resting spot on trueNAS.

You could probably use a command hook in Unpackerr to move the files after extraction. That's assuming the folder limitation is something you can deal with.

**Comment by Hizakix92** [comment]
I ended up just setting up a cronjob to run every 30ish minutes against /mnt/storage/Target. The job just moves the zip directories into myDL for extraction. I will look in to command hooks for moving the files after download. 

I appreciate your assistance in this. 

Thanks!

**Comment by davidnewhall** [comment]
> The job just moves the zip directories into myDL for extraction.

You've probably figured it out by now, but just make sure the script re-creates `myDL` every time it puts new files into it. Unpackerr just needs to see that new folder, then it will extract it.

Wish you the best!
