### ISSUE TITLE
How do I parse the logs?

### ISSUE THREAD

**Issue by seglo** [Unpackerr/unpackerr#319]
I added unpackerr to my stack and it eagerly found a bunch of archived files it started to unpack. I let it run over night. I think it's idle now, but I'm not really sure how to read most recent status logs.

```
2023/06/30 07:35:12 [Unpackerr] Queue: [133 waiting] [0 queued] [0 extracting] [32 extracted] [0 imported] [0 failed] [0 deleted]
2023/06/30 07:35:12 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
```

It's claimed `133` waiting since the beginning. Is this an unpackerr queue (if so, what is "queued" for?) The number hasn't decreased since I started the daemon.

**Comment by davidnewhall** [comment]
There's more logs lines to fill in the gaps. That's how many items are in your starr queues, waiting for you to do something with them.

**Comment by davidnewhall** [comment]
It's also strange to see 32 items extract, none finished and none imported. It seems like your starr app(s) not behaving correctly.

**Comment by davidnewhall** [comment]
@seglo Do you still need assistance with this?
