### ISSUE TITLE
Download client offline would cause Unpackerr to assume download imported 

### ISSUE THREAD

**Issue by yegle** [Unpackerr/unpackerr#321]
When the download client was temporarily offline, Unpackerr will assume there's no pending download, and mark the downloads as "imported".

In Whisparr: `Unable to communicate with qbt. The operation was canceled.`

A couple minutes later I got the notification via Telegram:

```
Imported
    
Title: XXX
App: Whisparr

Path: /downloads/whisparr/XXX
```

**Comment by yegle** [comment]
Hmm, when the download client is back online Unpackerr will continue processing all pending downloads.

So I guess the only thing we need to change here is, inhibit notifications if 1) Activity is empty, and 2) download client is not available at that time.

**Comment by davidnewhall** [comment]
Unfortunately, Unpackerr has no way to know if thew download client is offline or not.

**Comment by davidnewhall** [comment]
I've been thinking about this... It's probably possible to track the items more, but it sure gets complicated. I'm not sure I want to add more code that could introduce more bugs to fix the occasional "bad" notification. 

Seem reasonable?

**Comment by yegle** [comment]
It's occasionally annoying: I'm running qbittorrent on a less powerful machine and the hashing at the end of a download often render qbittorrent unresponsive. Multiple downloads completed over a short period of time would cause a repeated "X imported" / "X extracting" / "X extracted, awaiting import" notifications.

If fixing this would make the code more complicated I think it's okay to leave it as-is.

**Comment by davidnewhall** [comment]
The current relationship between unpackerr and Starr apps is simple. All it does is check the queue every couple minutes. If something disappears from the queue it considers it imported. That's it. That's how it works. I don't currently have a good solution in mind to make it better, or make it know if the downloader is offline. There may be other api calls unpacker could make, but all of that introduces more complexity and the potential for more bugs. I'll keep thinking about it, and I appreciate your understanding of the situation.
