### ISSUE TITLE
Unable to unrar multirar files

### ISSUE THREAD

**Issue by JordiKing10** [Unpackerr/unpackerr#325]
Im using it to automate the download stack from jellyfin, it supposed to unrar multirar files or is not planned?

**Comment by davidnewhall** [comment]
Yes.

**Comment by JordiKing10** [comment]
No, isnt working m8

**Comment by davidnewhall** [comment]
How do you know?

**Comment by davidnewhall** [comment]
This error message says it can't find the folder the rar files are in.  This indicates a misconfiguration. Did you mount `/downloads` the same way in Unpackerr as you did in Radarr? https://unpackerr.zip/docs/unpackerr/troubleshooting

**Comment by JordiKing10** [comment]
It only happens to me when they are multi-rar files. It has occurred about 5/6 times, and I have approximately 130 movies.

docker-compose.yml:

unpackerr:
    container_name: unpackerr
    image: hotio/unpackerr
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
      - UN_FOLDER_0_DELETE_AFTER=10m
      - UN_FOLDER_0_DELETE_FILES=false
      - UN_FOLDER_0_DELETE_ORIGINAL=true
      - UN_FOLDER_0_MOVE_BACK=false
      - UN_FOLDER_0_PATH=/data/transmission/downloads/complete
      - UN_RADARR_0_API_KEY=*removed*
      - UN_RADARR_0_DELETE_DELAY=5m
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_URL=http://192.168.1.240:7878
      - UN_SONARR_0_API_KEY=*removed*
      - UN_SONARR_0_DELETE_DELAY=5m
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_URL=http://192.168.1.240:8989
    volumes:
      - ./unpackerr:/config
      - ./unpackerr/data:/data
      - /data/transmission/downloads/complete:/downloads
    restart: unless-stopped
    
 It cant be any config mistake?

**Comment by davidnewhall** [comment]
> It only happens to me when they are multi-rar files.

Attach a log file so I can see what you see.

> It cant be any config mistake?

Share the compose for Radarr so I can determine this.

**Comment by davidnewhall** [comment]
Change this volume mount 
```
- /data/transmission/downloads/complete:/downloads
```
to 
```
- /data/transmission/downloads:/downloads
```
will likely fix your problem. Please let me know if you need additional assistance.

**Comment by pando85** [comment]
I'm experiencing the same problem. Just multi rar files fails. The path is correct int Radarr API and it looks like unpackerr is looking for the `title` instead of the `outputPath`:

Radarr API:
```
      ...
      "title": "[Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]",
      "statusMessages": [
        {
          "title": "Found archive file, might need to be extracted",
          "messages": []
        }
      ],
      "outputPath": "/datasets/peliculas/download/El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]",
      "id": 952822445
    },
    ...
```

Unpackerr:
```
[INFO] 2023/08/20 10:20:18 [Radarr] Completed item still waiting: [Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one], no
 extractable files found at: /datasets/peliculas/download/[Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one] (stat err: 
stat /datasets/peliculas/download/[Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]: no such file or directory)        
[INFO] 2023/08/20 10:20:18 [Radarr] Completed item still waiting: [Bitsearch.to] Plan de escape 3 (2019) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.nucleo
hd.com], no extractable files found at: /datasets/peliculas/download/[Bitsearch.to] Plan de escape 3 (2019) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.nuc
leohd.com] (stat err: stat /datasets/peliculas/download/[Bitsearch.to] Plan de escape 3 (2019) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.nucleohd.com]: n
o such file or directory)   
```
The directory exists inside unpackerr and it has permissions to read it (it is working with other files):
```
unpackerr-6dc8b9685b-dq44l:/app$ ls "/datasets/peliculas/download/El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]"
ATOMIXHQ ONE.url
El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one].part1.rar
El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one].part2.rar
El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one].part3.rar
PCTNOTICIAS TELEGRAM.url
```

**Comment by davidnewhall** [comment]
@pando85 Would be helpful for me if you enabled debug, and provided the log file after letting it run for 10 minutes.

**Comment by pando85** [comment]
Nothing new:
```
[INFO] 2023/08/21 06:54:50.870766 sonarr.go:118: [Sonarr] Updated (https://sonarr.internal.grigri.cloud): 1 Items Queued, 1 Retrieved
[DEBUG] 2023/08/21 06:54:50.871319 handlers.go:217: Radarr: Errors encountered looking for [Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one] path: ["stat /datasets/peliculas/download/[Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]: no such file or directory"]
[DEBUG] 2023/08/21 06:54:50.871386 handlers.go:235: Radarr: Configured paths do not exist; could not find alternative path in error message for [Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]
[INFO] 2023/08/21 06:54:50.871444 handlers.go:90: [Radarr] Waiting for Start Delay: [Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one] (1m0s remains)
[DEBUG] 2023/08/21 06:54:50.871495 radarr.go:155: Radarr: (https://radarr.internal.grigri.cloud): completed (torrent:100%): [Bitsearch.to] El ultimo duelo (2021) [BluRay Rip][AC3 5.1 Castellano][www.atomixHQ.one]
```
It seems that it's looking by title not by `outputPath`.

**Comment by davidnewhall** [comment]
Definitely new things there, and that showed me some of what I needed to see. May I have the log file?

**Comment by davidnewhall** [comment]
I actually think I found the bug. It's some code that needs refactoring anyway, so guess now's a good time to do it. Thanks for the extra logging!

note to self: search for shoehorn, and remove all of it.

**Comment by davidnewhall** [comment]
If you're using in Docker, the `golift/unpackerr:unstable` tag will be updated in about 35 minutes with a potential fix. Please try it out and let me know. If you're not using Docker, you may [grab a binary here](https://unstable.golift.io).

**Comment by pando85** [comment]
Thank you very much, now extraction started :)
