### ISSUE TITLE
Calling plist_options is disabled! Use service.require_root instead.

### ISSUE THREAD

**Issue by ghazel** [Unpackerr/unpackerr#329]
https://github.com/golift/homebrew-mugs/blob/1dbba056845534c7f8c5346a8527ea1a4a2ea8f1/Formula/unpackerr.rb#L34

% brew install golift/mugs/unpackerr
==> Tapping golift/mugs
Cloning into '/opt/homebrew/Library/Taps/golift/homebrew-mugs'...
remote: Enumerating objects: 922, done.
remote: Counting objects: 100% (188/188), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 922 (delta 91), reused 188 (delta 91), pack-reused 734
Receiving objects: 100% (922/922), 122.50 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (430/430), done.
Tapped 11 formulae (25 files, 177.3KB).
Error: golift/mugs/unpackerr: Calling plist_options is disabled! Use service.require_root instead.
Please report this issue to the golift/mugs tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/golift/homebrew-mugs/Formula/unpackerr.rb:34

**Comment by davidnewhall** [comment]
Hello and thank you for your report!

This is probably where I drop support for home-brew. I can't even google `plist_options` anymore without finding nothing but a million GitHub tickets identical to this one. As if this ecosystem wasn't hard enough to be a dev in; they do this.

I'll accept a PR to fix it, but after October all home-brew _anything_ is getting removed.
