### ISSUE TITLE
Allow setting the `unpackerr` folder as immutable and then after the item is imported by Sonarr/Radarr make it mutable

### ISSUE THREAD

**Issue by onedr0p** [Unpackerr/unpackerr#333]
Hi 👋🏼 

It would be awesome if unpackerr could set the [immutable bit](https://www.tecmint.com/make-file-directory-undeletable-immutable-in-linux/) on the folder while extracting the files and then make it mutable again after import into sonarr/radarr.

The reason I am suggesting this is that I have auto cleanup tasks that might interfere with unpackerr extracting files and this would make it so the folder is not deleted while an item is being extracted.

Thanks!

**Comment by davidnewhall** [comment]
Qbit-manage solved this somehow. Probably with a delay. Your auto cleanup could look for the _unpackerred folder and assume an extraction is happening?

**Comment by onedr0p** [comment]
Yeah I was already thinking about implementing it into my auto-clean up solution but this idea came up which would be a way to solve it for all linux users 😄

**Comment by onedr0p** [comment]
Closing this issue as it's a non-issue once the tools are aware of the unpackerr folders.

**Comment by davidnewhall** [comment]
That's good, because I really wasn't sure how to do this with the way the code abstracts the decompression to another library. Glad you got it working well!
