### ISSUE TITLE
[Request] Delete empty folder

### ISSUE THREAD

**Issue by nodiaque** [Unpackerr/unpackerr#334]
Hello,

Using unpackerr, there's a feature to delete the extracted file after extraction. It would be nice if it could also delete the folder if it's empty. My current configuration extract the file in a temp folder named <torrent name>_unpackerred and then move the file back in <torrentname>. After that, the corresponding *ar program import the extracted file and change the category in qbittorrent. By changing the category, the content of the torrent is then moved to another folder. This leave the extracted file in the folder. Unpackerr then pass 5 minutes after and delete the file but leave the empty folder.

Thank you

**Comment by davidnewhall** [comment]
Can you make qbit change the category more slowly and set the delete_delay in unpackerr to maybe `1m`? That may solve it. 

Basically, get qbit to move the download files after unpackerr cleans up.

**Comment by davidnewhall** [comment]
Your request seems reasonable, and I'll see if we can do that. re: delete folder if it's empty after deleting extracted item.

**Comment by davidnewhall** [comment]
Hello @nodiaque,

Please grab unstable and let me know if that solves your problem. In docker it's `golift/unpackerr:unstable` otherwise head over [here](http://unstable.golift.io).  This is the entire change: https://github.com/Unpackerr/unpackerr/pull/332/commits/23eb84e4bfc2ab3ce802c66289064b4c4b3b364a

**Comment by nodiaque** [comment]
Ok I installed it, I'll get a torrent and check if it work. Thanks!

**Comment by davidnewhall** [comment]
Once you tell me it works, I'll cut a new release.

**Comment by nodiaque** [comment]
Sorry for my late reply, took a long time before I get a packed torrent.

It seems to work great but I found one caveat which I don't know how we can fix it, maybe we information from sonarr/radarr/qbittorrent.

Just had a torrent that had multiple rar file in different subfolder, like:
the package s01
- s01e01
-- s01e01.r01, r02.... rar
- s01e02
-- s01e02.rar

etc.

When the delete is ran, it delete all s01e0x folder which is very good, but then the torrent folder at the root is kept (the package s01).

Unsure if I'm clear?

**Comment by davidnewhall** [comment]
> Unsure if I'm clear?

Why try to be clear when you can share a screenshot? 

Are you describing a torrent with more than 1 season in it? Sonarr does not even support those.

**Comment by nodiaque** [comment]
I didn't though about screenshot, sorry. No it's a 1 torrent for a whole season and each episode is in it's own folder, compress in a different rar. At the end, it properly deleted each episode folder but the base folder remained

![image](https://github.com/Unpackerr/unpackerr/assets/324425/27df47aa-691e-44ca-977b-3dcb6c9a13e2)
![image](https://github.com/Unpackerr/unpackerr/assets/324425/efe097b5-87f0-4a53-bc01-9b8085227f29)

**Comment by davidnewhall** [comment]
Gotcha, I don't think this will be something Unpackerr can fix for you. The risk of the app crawling too high up and deleting your `/downloads` directory (because it was empty) becomes real when I try to solve this. You could look into packer executing a script when it finishes, then you can control what to delete.

**Comment by davidnewhall** [comment]
It's a lot of code to do what you're asking. Checking for an empty folder was not very much new code, so solving the original problem was easy. Unpackerr is an extracting tool. You'll need another solution for empty folders. You can solve this problem may other ways that do not involve more code and potentially more bugs in Unpackerr.

> I was wondering, why not verifiy from the download path directly? 

It's not available when the delete is issued.

**Comment by nodiaque** [comment]
Ok, I though it might be saved somewhere and you could have the information. Like we said, asking won't bite ;)

I had already another program doing the cleanup, qbitmanage. But their tool is not very unpacker friendly and it start deleting orphaned file from the torrent folder or even while it's unpacking, or when sonarr is unpacking. I tried telling them but they refuse to make check before deleting saying "it's because I'm using unraid bad" and said to try here. I'll simply run a user script in unraid that clear empty folder then. My goal was to build on top of another existing solution simply.

Thanks again for your help!

**Comment by davidnewhall** [comment]
Sounds like you talked to @bakerboy448. Sorry about that experience.

**Comment by bakerboy448** [comment]
The issue described was unpackerr was not cleaning up the extracted files.

ref https://github.com/StuffAnThings/qbit_manage/issues/345

**Comment by nodiaque** [comment]
problem was qbitmanage cleanup while the torrent is still during import or unpacking. I implemented all fixe you said which fixed the cleanup of _unpackerred folders, but it didn't solve the file being unpacked into the torrent folder getting removed either while unpacking or while importing. A simple Starr check to see if the torrent is still waiting/during import before a cleanup would suffice, but you refuse that stating bad io. So instead of making the program more robust and prevent false positive, you decide to blame performance. That's bad coding my friend, but it's your software so I didn't argue more just like here, I don't argue more and I'll implement my own solution.

Thank you

**Comment by bakerboy448** [comment]
qbm has no communication nor any interaction with starr nor are their any plans to.

an ideal setup that facilitates hardlinks rather than io intensive copies means the only case where qbm would remove unpacked files as orphaned would be a perfect storm where in roughly the same minute, unpacked files exist; starr has not yet or is refreshing the queue and has not begun the imports - which would be near instant - due to hardlinks or running qbm so frequently it is checking faster than starr can import....again using hardlinks

**Comment by nodiaque** [comment]
So if a starr app is faulty, boom qbitmanager will clear it. QBM is set to run each 30 minutes, but when you download, the 30 minutes mark can happen at anytime. Hardlink won't solve the problem where unpacker is extracting the file. Since you don't want to communicate with Starr, you still have already a communication with qbittorrent. Something could be very easily added to check if the torrent is still in a download category since it already know which category are download and library and skip these. You already have this information for many other check thus it's nothing to do. 

But yeah, I'll just make my own cleanup script instead of trying to improve imperfect solution that as no fail safe and think that everyone should have only 1 way of doing things as a holy grail. BTW, "my" way of doing thing is as popular if not more then trash way, and there's other way too.
