### ISSUE TITLE
unpackerr.log permission

### ISSUE THREAD

**Issue by nodiaque** [Unpackerr/unpackerr#344]
Hello,

I see in my environment (unraid) that the unpackerr.log is saved with permission 700. It would be great if we could set a variable to change these value for something else.

Also, I tried using the variable GUID/GID PUID/UID to change the user and group of the docker but it doesn't work, it always save as root.root, which prevent reading the log file except if I'm root.

Thank you

**Comment by davidnewhall** [comment]
> I tried using the variable GUID/GID PUID/UID to change the user and group

The Go Lift container does not use environment variable to set the uid and gid. Just pass `--user uid:gid` to `docker run` when you start the container. Explained here: https://unpackerr.zip/docs/install/unraid#permissions

**Comment by nodiaque** [comment]
Ah great, sorry it seems I skipped that in the doc. Working great!
