### ISSUE TITLE
Feature Request: Allow multiple download paths for each application

### ISSUE THREAD

**Issue by NostalgicGnome** [Unpackerr/unpackerr#346]
I have multiple save paths for downloads for each application unpackerr talks to. It would be swell to be able to add them in a comma separated list in the docker template or something. I tried setting the download path for one application to the parent path of both of its download directories, but I still got errors because it couldn't find the file in that directory specifically.

**Comment by davidnewhall** [comment]
Sorry missed this issue. You can specify multiple paths. If you need help configuring the app please share your current configuration. Documentation can be found here: https://unpackerr.zip/docs/install/configuration
