### ISSUE TITLE
no extractable files error inside folder with .rar

### ISSUE THREAD

**Issue by instrumentek** [Unpackerr/unpackerr#359]
Hi; looking for help solving this logged error and no file extraction:

system: synology 918+ DSM 7.2 installed in container manager
Symptom: unpackerr not unpacking files

Errors:
```
"no extractable files found at: /volume1/downloads/**FILE NAME** (stat err: stat /volume1/downloads/**FILE NAME**: no such file or directory"
"[INFO] 2023/11/13 03:12:11 [Sonarr] Waiting for Start Delay: **FILE NAME**  (1m0s remains)"
"[INFO] 2023/11/13 03:19:11 [Unpackerr] Queue: [7 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]"

```
Config file:
```
[[sonarr]]
  url = "http://192.168.1.65:8989"
  api_key = "1d45454d9**************a9a8b25f73"
  paths = ['/volume1/downloads']
  protocols = "torrent"
  timeout = "10s"
  delete_orig = false

```
Ive opened up all the permissions and confirmed my UID and GID numbers are programmed into docker

**Comment by davidnewhall** [comment]
How did you install unpackerr?

**Comment by instrumentek** [comment]
Hi thanks for the reply. I will attatch the exported container settings. 
[unpackerr.json](https://github.com/Unpackerr/unpackerr/files/13335602/unpackerr.json)
currently I have mounted "/downloads" which i assume is really "volume1/downloads" where the downloads are located. I will try playing with the file mounting inside docker and specifically include volume1.

**Comment by instrumentek** [comment]
So it wont let me directly add "volume 1" Its has a dropdown for the folder, and a text editor field.  I have tried several options including: 
"/downloads___________/downloads"
"/downloads___________/splat"   
"/downloads___________/splat.splat"

I cant leave the second text box blank and the results in the container description show:
"/volume1/downloads:/downloads:rw"
"/volume1/downloads:splat:rw"
"/volume1/downloads:/splat.splat:rw"

all 3 end with the same result:
`[INFO] 2023/11/13 14:43:29 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
[INFO] 2023/11/13 14:43:29 [Unpackerr] Queue: [8 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
`
unpackerr is connecting to sonarr so i assume it is correctly accessing the conf file? which is also specified in the volume mounting 

`[INFO] 2023/11/13 14:42:29  => Using Config File: /config/unpackerr.conf` 
"/docker/unpackerr___________/config"
or in the descripction as:
"/volume1/docker/unpackerr:/config:rw"

I don't understand how the names are different conf =/= config??

the above was specified in a tutorial i followed.

**Comment by instrumentek** [comment]
OK, so it turns out the problem is my lack of understanding of container manager..... 
It works if the config file is set to /downloads and the container manager has the native /downloads mapped to /downloads inside the container. I thought that volume settings was all referencing back to native directories on the DSM not folders inside docker.

please close this thread, sorry to waist your time

**Comment by bakerboy448** [comment]
/volume1/downloads does not exist in the container as you've called it /downloads within the container

[the (community) install docs](https://drfrankenstein.co.uk/2022/07/02/unpackerr-in-docker-on-a-synology-nas/) from the [website](https://unpackerr.zip/docs/install/choosemethod#other-guides) should have helped with this.  What tutorial did you follow?

If download clients are downloading to /volume1/downloads you need to mount that exactly into the container or use the path in the config file to tell unpackerr what the equivalent is.  https://unpackerr.zip/docs/unpackerr/troubleshooting
