### ISSUE TITLE
[feature] Option to Extract Archives Without Requiring a Subfolder

### ISSUE THREAD

**Issue by zampierilucas** [Unpackerr/unpackerr#363]
**What's the idea?**
How about an option in Unpackerr to extract files directly without needing to use a subfolder?
It could just use the arquive name as the folder to extract.

**Why it could be cool:**
- I (and I'm guessing others) download a bunch of stuff to a single folder, like 'Downloads'. It'd be super convenient if Unpackerr could just unzip everything right there, without putting them into separate subfolders.

Thanks for considering it, and for making a great tool!

**Comment by davidnewhall** [comment]
It wasn't designed to watch a browser download folder. It's designed to watch a torrent app download folder. 

Making it work without a sub folder was always a challenge. I'll leave this request open, but I probably won't add the feature. I'd rather spend my time adding unit tests, so changes like this are easier to implement safely.

**Comment by zampierilucas** [comment]
Yeah, I get it, it's out of the scope of this project. 
Either way, thank you for considering.
