### ISSUE TITLE
Convert RAR5 archives to ZIP

### ISSUE THREAD

**Issue by gotson** [Unpackerr/unpackerr#367]
Hi,

i would be interested in having items in the watch folder to be converted if they are in RAR5 format to ZIP. [Komga](https://komga.org/) can't read RAR5 files, but i need the files to remain in an archive (RAR4 or ZIP), those are comic book archives (CBR/CBZ).

Would be fantastic if Unpackerr could convert instead of just unpacking, under specific scenario.

Feel free to close if this is out of scope of the project.

**Comment by davidnewhall** [comment]
This is probably out of scope for what Unpackerr does. You may be able to setup a custom format/scores in Readarr to avoid RAR downloads.
