### ISSUE TITLE
unpackerr lost connection to sonarr / radarr after working for some time

### ISSUE THREAD

**Issue by instrumentek** [Unpackerr/unpackerr#372]
system: synology 918+ DSM 7.2 installed in container manager
Symptom: unpackerr not unpacking files. was previously working then stopped. 

Errors:
`[ERROR] 2024/01/06 14:28:03 Sonarr (http://192.168.1.65:8989): api.Get(v3/queue): httpClient.Do(req): Get "http://192.168.1.65:8989/api/v3/queue?includeUnknownSeriesItems=true&page=1&pageSize=500&sortDirection=ascending&sortKey=timeleft": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

Unpackerr config:
```
[[sonarr]]
  url = "http://192.168.1.65:8989"
  api_key = "mykey*****************mykey"
  paths = ['/SonarrDownloads']
  protocols = "torrent"
  timeout = "30s"
  delete_orig = false
```
Progress:
I believe the problem is connectivity between unpackerr, docker and sonarr. I intentionally put in the incorrect key and changed port and IP numbers inside the unpackerr conf and get the same code. the only thing changed since the time it was working where some network settings like the VPN provider and the gateway.

I have tried:
- changing all the network settings back (this was a while ago when it was changed so my best attempts)
-  changing to DHCP then back to static, changing the DNS to manual and automatic, changing the gateway
- The address inside unpackerr put into a browser and it opens sonarr fine
- re coping the API key
- changing security parameters inside sonarr 
- radarr shows the exact same error 
- restarting the DSM 
- increasing the timeout time to 30s
- I tried pinging the docker container it fails to connect. But I'm not sure if that's even possible or how the docker bridge network connection behaves.  
Thanks for any advice

**Comment by austinwbest** [comment]
It didn't lose connection, it times out after waiting 30s for a response

**Comment by instrumentek** [comment]
More info:
From the logs on the same day it stopped working the VPN was changed.

it updated successfully: 
`[INFO] 2023/12/12 21:55:51 [Sonarr] Updated (http://192.168.1.65:8989): 0 Items Queued, 0 Retrieved`

the first error:
`[ERROR] 2023/12/12 22:01:11 Sonarr (http://192.168.1.65:8989): api.Get(v3/queue): httpClient.Do(req): Get "http://192.168.1.65:8989/api/v3/queue?`

logs from DSM on the 12'th

```
Info | System | 12/12/2023 12:45 | xxxxxxx | VPN profile [Connection] was   created.
Info | System | 12/12/2023 12:44 | xxxxxxx  | VPN profile [AirVPN] was deleted.
Info | System | 12/12/2023 12:35 | xxxxxxx | VPN profile [AirVPN] was created.
Info | System | 12/12/2023 12:34 | xxxxxxx  | VPN profile [AirVPN] was deleted.
Info | System | 12/12/2023 12:32 | xxxxxxx  | VPN profile [AirVPN] was created.
Info | System | 12/12/2023 12:31 | xxxxxxx  | VPN profile [AirVPN] was deleted.
Warning | System | 12/12/2023 12:22 | SYSTEM | VPN profile [NordVPN] was   disconnected by server.
Info | System | 12/12/2023 12:22 | xxxxxxx  | VPN profile [NordVPN] was   disconnected by user.
Info | System | 12/12/2023 12:22 | xxxxxxx  | VPN profile [AirVPN] was created.
Info | System | 12/12/2023 10:40 | xxxxxxx  | VPN profile [NordVPN] is connecting   to [xxxxxxx ]. (protocol[OpenVPN], 
```

**Comment by instrumentek** [comment]
> It didn't lose connection, it times out after waiting 30s for a response>

I assumed its not connecting to sonarr anymore because I get the same errors if I enter incorrect credentials into the unpacker conf. I should also add; I do not use a firewall and I disabled the router firewall. sonarr / radarr are outside docker directly on the DSM. I'm assuming some communication problem surpassing that barrier.

**Comment by davidnewhall** [comment]
Attach the log file please.

**Comment by instrumentek** [comment]
SOLUTION: 
disable and delete VPN connection, disable "enable multiple gateways" option, set gateway to 8.8.8.8. this fixed the issue.

I have yet to try and reenable things to determine what killed it exactly. I want to wait untill all the extraction back log is done. The goal being to have a functional VPN

**Comment by davidnewhall** [comment]
You isolated sonarr with the VPN and unpackerr could not reach it. Removing the VPN removed the isolation. Need to figure out how to use docker networking to connect from container to container without the host ip.

**Comment by instrumentek** [comment]
it's interesting because nord VPN worked, when i switched to airVPN is when the problem occured. Sonar runs locally on this DSM. I'm not networking expert but perhaps creating a rule in a routing table?

**Comment by davidnewhall** [comment]
I don't use Synology or a VPN. I have very little ability to help you troubleshoot that part of this equation.

**Comment by instrumentek** [comment]
OK, thanks for input. problem is outside of unpackerr. 

**please close issue**
