### ISSUE TITLE
Unpackerr partially fails to use lidarr output path when said path is a full path to a single file.

### ISSUE THREAD

**Issue by ruifung** [Unpackerr/unpackerr#373]
Example output path from Lidarr: /downloads/Torrents/lidarr/(Download Release)/(Download Release).rar

Error in unpackerr:
```
[INFO] 2024/01/15 10:04:40 Extraction Started: (Download Release), items in queue: 0                                                                                                                   
[INFO] 2024/01/15 10:04:43 Extraction Error: (Download Release): os.MkDirAll: mkdir /downloads/Torrents/lidarr/(Download Release)/(Download Release).rar: not a directory
```

It appears to be working under the assumption that the output path is always a folder, which does not appear to be the case here. Lidarr can have an output path as a single file sometimes?

Or rather, it says it fails to unpack, but if you look in the folder, it's unpacked but it keeps logging errors due to this and keep retrying it for some reason.

**Comment by davidnewhall** [comment]
Unfortunately torrents that lack folders are not compatible with starr apps. Once unpackerr extracted the music files from that rar file there is no where it can put the files where Lidarr will find and import them. If the download pointed to a folder instead of a file, the extracted content can be put into the folder where the starr app is able to locate it. 

I've heard that some torrent clients may have a setting to always create a folder. You may also be able to setup custom formats to avoid release groups that create incompatible torrents. Good luck!

**Comment by davidnewhall** [comment]
For what it's worth, the latest version of Unpackerr (0.13.0) will extract these items now. Lidarr still wont know how to import them though. Let me know how that works out for you!

**Comment by ruifung** [comment]
> For what it's worth, the latest version of Unpackerr (0.13.0) will extract these items now. Lidarr still wont know how to import them though. Let me know how that works out for you!

Sure. That's fine, and reasonably easy to work around by manual importing. I do wish lidarr supported download clients that are set to put everything in a subfolder though.

I'll report back eventually I guess.

**Comment by davidnewhall** [comment]
The passive voice at the end there makes it sound like you expect me to do something else. Any suggestions?

**Comment by ruifung** [comment]
Oh no, I can hardly expect more to be done on this side when the root cause of the issue is in the *arr apps having no idea how to handle a download client that's creating a subdirectory and just being generally confused.

Just having it unzipped and not treated as an error in unpackerr is sufficient. Even though previously it would somehow unpack it and error out and leave the unpackerr suffixed folder behind.
