### ISSUE TITLE
Add icon to the dashboard icons project

### ISSUE THREAD

**Issue by joestump** [Unpackerr/unpackerr#374]
Looks like a PR was submitted, but closed https://github.com/walkxcode/dashboard-icons/pull/308

If someone can point me at the assets, I can try and PR it upstream. Adding this for tracking purposes.

**Comment by davidnewhall** [comment]
We tried to use that project, but found that contributions were difficult to make. We forked it and maintain our own now. Here: https://github.com/Notifiarr/images

It also contains the [icon for unpackerr](https://github.com/Notifiarr/images/blob/main/icons/unpackerr.png). Good luck!
