### ISSUE TITLE
ghcr semver support

### ISSUE THREAD

**Issue by webysther** [Unpackerr/unpackerr#383]
Any chance to put the images on `ghcr.io/golift/unpackerr:0`?

**Comment by davidnewhall** [comment]
I'm not in a hurry to make semantic versioning work on GHCR. I'd look at a pull request though.

**Comment by davidnewhall** [comment]
Seems like it worked. 0 is tagged now.

**Comment by webysther** [comment]
Thanks a lot! Hub docker quota limit is killing me!
