### ISSUE TITLE
Unpack OpenSSL encrypted files

### ISSUE THREAD

**Issue by STaRDoGG** [Unpackerr/unpackerr#389]
Another enhancement in addition to the previous one I added, would also be the ability to extract OSSL files; i.e. files with filenames like this:

> mia-2024-01-22-2300.sql.bz2.enc

That particular file is a nightly db backup that gets OpenSSL encrypted and sent over to DropBox, but people OpenSSL encrypt all kinds of stuff.

I wrote a DOS .bat script you can use if interested. In this case it just uses the encryption pw (`thepassword`) when extracting (no pem file), but it would be trivial to add that if wanted, as well:

```
@echo off

rem + ------------------------------------------------------------------------------------------- +
rem |                                                                                             |
rem | OpenSSL File Decrypter w/Optional 7Zip Unpacker                                             |
rem |                                                                                             |
rem | J. Scott Elblein                                                                            |
rem |                                                                                             |
rem | REQUIREMENTS:                                                                               |
rem |   - openssl.exe must be in your Windows Path                                                |
rem |   - 7z.exe must be in your Windows Path. In this case, it's in a path within my FMT folder  |
rem |                                                                                             |
rem | USAGE:                                                                                      |
rem | Decode-OpenSSL-File-Cline.bat <.enc file to decrypt> [<decrytpion pw>]                      |
rem | If no decryption pw was passed, defaults to the one on line w/"DEFAULT PW".                 |
rem |                                                                                             |
rem |                                                                                             |
rem | TIPS:                                                                                       |
rem |   - Set your default PW below, and comment out the 'pause' at the end if you want it too    |
rem |     all happen in one automatic motion.                                                     |
rem |   - If you set a default pw, you can also just drag & drop the .enc file onto this .bat.    |
rem |                                                                                             |
rem | TODO(?):                                                                                    |
rem |   - Add flags to auto-select the Extract & Pause options, for a smooth experience.          |
rem |                                                                                             |
rem + ------------------------------------------------------------------------------------------- +

rem Clear screen to make it all cleaner & easier to read
cls

if "%1"=="" (
    echo Usage: %0 ^<fn^> [^<pw^>]
    goto :eof
)

set fn=%1
set pw=%2

rem + -------------------------------------------------------------------------------- DEFAULT PW +
rem | If no pw was passed to the cline, default to the pw added below.                            |
rem + ------------------------------------------------------------------------------------------- +

if "%pw%"=="" set pw=thepassword

rem + ------------------------------------------------------- EXTRACT ROOT NAME WITHOUT EXTENSION +

for %%F in ("%fn%") do set rootname=%%~NF

rem + ----------------------------------------------------------------------------------- DECRYPT +

openssl enc -d -a -aes-256-cbc -in "%fn%" -out "%rootname%" -pass pass:%pw%

echo.
echo ^+ -------------------------------------------- ^+
echo ^| DECRYPTION:  Complete                        ^|
echo ^| OUTPUT FILE: %rootname%
echo ^+ -------------------------------------------- ^+
echo.

rem + ----------------------------------------------------------------------------------- EXTRACT +

set /p extract_choice=Do you want to extract the file? (Y/N): 
if /i "%extract_choice%"=="Y" (
    "%FMT%\Misc\Compression\7Zip\7z.exe" x -y -mmt "%rootname%" -o"%rootname%-extracted" *
    echo.
    echo ^+ -------------------------------------------- ^+
    echo ^| EXTRACTION: Complete                         ^|
    echo ^+ -------------------------------------------- ^+
    echo.
)

pause
```

**Comment by davidnewhall** [comment]
I'm not super fond of the idea of adding proprietary decryption routines to solve your problem. You can add AES encryption to a 7-zip archive without proprietary encryption. That may be a better solution for you, and unpackerr supports that natively.

**Comment by STaRDoGG** [comment]
No problem, it's just another idea to enhance Unpackerr. =)

Just so I'm clear for future reference though, which part of it is proprietary?

![image](https://github.com/Unpackerr/unpackerr/assets/1524526/054f76e4-9ff6-45ea-9028-1f7bae04447a)

**Comment by davidnewhall** [comment]
The part that's proprietary is using the AES 256 cipher in openssl to encrypt a 7zip file. Where does that happen in the wild?

**Comment by davidnewhall** [comment]
> no, you're misunderstanding the process.

I actually had it nailed to a tee. You sent me a link to the docs which I read before responding.

>  the main thing is just having the file itself encrypted as it's going over the wire from point A to point B

Encryption over the wire is done by HTTPS or SCP. 

> Notice 7z actually has no part in the encrypting/decrypting

That's what makes PHPBU's solution proprietary. You're actually confusing the situation by using (referring to) 7zip and not bunzip2.

> not an ultra important feature to add, but a suggested enhancement

Unfortunately the code in unpackerr is not laid out in a way to make this easy. Specifically, decrypting files that use ciphers not built into a compression specification. Unpackerr decompresses, it does not decrypt, and I'm not sure that's something I want it to do. For a few reasons. If you need to hear them let me know.

> Notice 7z actually has no part in the encrypting/decrypting process

If it did, this wouldn't be proprietary. Instead of let PHPBU pick the encryption and compression, can it run your script so you can compress and encrypt your own way? I'd suggest using 7zip or rar encryption so you can take advantage of unpackers built-in support.


Let me re-state this so it's more clear: **The part that's proprietary is using the AES 256 cipher in openssl to encrypt a file.** 
Why? Because nothing really does that out of the box. A lot of folks would argue that it's a weak cipher and you should use something else. This is nice: https://github.com/FiloSottile/age I might even consider supporting this (proprietary) encryption format.  Mostly because it's 100x simpler than openssl and more secure for noobs.

Hope this helped. Good luck!

**Comment by STaRDoGG** [comment]
> > no, you're misunderstanding the process.
> 
> I actually had it nailed to a tee. You sent me a link to the docs which I read before responding.

> The part that's proprietary is using the AES 256 cipher in openssl to encrypt a ~~7zip~~ bzip2 file. 

You corrected it after. ;)

You said "use AES to encrypt a 7zip file", which isn't what I was doing. I was addressing specifics.

Either way, you might wanna duke that whole argument out with an AI droid, lol...

![image](https://github.com/Unpackerr/unpackerr/assets/1524526/9b02a7e9-b34c-4550-8acd-c0980efe499c)

> > the main thing is just having the file itself encrypted as it's going over the wire from point A to point B
> 
> Encryption over the wire is done by HTTPS or SCP.
> 

You're making the assumption that _my_ use case is going to be the exact use case for literally un unknown, potentially very large, number of _other_ users, who may _not_ use https or scp to transfer their files, while still wanting to OSSL encrypt their files.

You asked for an example _I'd_ be using it for, and I gave you my example.

> > Notice 7z actually has no part in the encrypting/decrypting
> 
> That's what makes PHPBU's solution proprietary. You're actually confusing the situation by using (referring to) 7zip and not bunzip2.

I'm not confused at all... 

You are conflating the encrypt/decrypt routines, with the compress/decompress routines. It could be 7zip, bunzip2, or any other capable decompression software. Btw, PHPBU [isn't proprietary software either](https://github.com/sebastianfeldmann/phpbu/blob/main/LICENSE); it's open-source.

From top to bottom, A to Z, there's no point in which any of this is proprietary.

> Let me re-state this so it's more clear: **The part that's proprietary is using the AES 256 cipher in openssl to encrypt a file.** 

Ok; and I counter with re-stating as well:

![image](https://github.com/Unpackerr/unpackerr/assets/1524526/900cf1b1-9154-4fa2-83d9-4753ad2a5c75)

Anyway, I'm closing this issue as well, as dead in the water.
