### ISSUE TITLE
Add an option to leave the finished unpacked file in the /unpacker subfolder or append suffix

### ISSUE THREAD

**Issue by NGDM** [Unpackerr/unpackerr#393]
I'm encountering an issue with Unpackerr and qBit Manage.

If for any reason (delay, downtime, TBA episode title,...) Sonarr doesn't import the extracted file right away, it's possible QBM comes in and identifies it as an orphaned file and removes it.

If there was a way for QBM to identify this finished extract (by subfolder, or by suffix) we could prevent this situation.

I'm not knowledgeable enough into the *Arr import process to know if this would be an issue or not.
Hope this can be implemented in some way.

**Comment by austinwbest** [comment]
Have you asked the qbm people about it? You are far from the only one who uses these two apps together and I'm sure there is a solution there for that

**Comment by davidnewhall** [comment]
Every time someone asks about this I suggest talking to the qbit-manage team. The team usually says something like "Only run the orphan finder once or twice a day."

**Comment by NGDM** [comment]
I saw an issue exists for this on the qbm github (https://github.com/StuffAnThings/qbit_manage/issues/345).
Running it less often is indeed a suggestion but is not what you want for the category/share-limit/... functionalities. 
So proposed solution now is to let QBM check for the torrent category to decide if it should be scanned for orphan files or not, but it's low priority right now.

So an option to leave the unpacked file in a subdirectory (or a with a suffix) would fix this and might be less effort?

**Comment by davidnewhall** [comment]
Can you explain to me why leaving the scanner at the default of 1440 minutes is insufficient?

Your proposed solution will likely make it difficult if not impossible for starr apps to import the extracted file(s). I still think you should speak with @bobokun about the problem (and less your proposals) so he can provide a proper configuration for qbm.

**Comment by NGDM** [comment]
Didn't know they changed the default to 1440. 
I'll try that, it might virtually fix the issue, although in case of a 'TBA'-title delay this could take more than 24h.
Also, I imagine share_limits might be ignored for 24 hours because of this.
Public torrents could saturate my other seeds and internet connection if it's not set to the right limits for example.

**Comment by davidnewhall** [comment]
Sounds like QBM is interested in making this work properly. Unpackerr cannot fix this since the problem is QBM deleting extracted unimported files.
