### ISSUE TITLE
Lidarr not used, but container wouldn't run

### ISSUE THREAD

**Issue by AustinTylerDean** [Unpackerr/unpackerr#397]
It might have been the fact that I changed the the Lidarr default url to include my IP address? But either way I didn't fill in the Lidarr API and it wouldn't run.

Maybe you can sprinkle some magic that only errors out if the API is used. But I got it running by deleting the Lidarr URL and API lines in the container config screen.

Thanks for keeping this updated! I has no idea what I would do without it.

**Comment by davidnewhall** [comment]
Providing an invalid configuration (a url without an api key) generates an error on startup. If you're asking me to change that, sorry no, too many folks would be negatively affected. If you're asking for something else, please elaborate.

**Comment by AustinTylerDean** [comment]
The description states that leaving the API blank is the directive for not
using the service. I'm just saying that isn't technically true. When
downloading the container, the Lidarr URL field is automatically populated.
This is confusing. I would not populate the Lidarr URL, or make the note
state that nothing should be in either entry, or do what you say you won't.

Or not, just trying to be helpful. There's probably a lot of idiots like me
out there.

**Comment by davidnewhall** [comment]
Is this an unRaid report or another OS that comes with pre-populated fields?

**Comment by AustinTylerDean** [comment]
Unraid container, yes. I don't exactly know what you mean by report,
forgive me!

**Comment by davidnewhall** [comment]
Which template did you use?

The one I maintain is here: https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/unpackerr.xml#L17-L18
And you can see it says:
> If you don't use one of Lidarr, Sonarr or Radarr, simply empty those two fields for that app and it wont be polled.
  
In bold even. The two fields it refers to are url and api key. Is that inaccurate?

**Comment by AustinTylerDean** [comment]
It clearly looks like I'm an idiot. But if you KNEW me, you'd probably
think the same thing.


I swear my eyes read "leave API blank" and nothing else, but you seem to
have that base covered.

Thanks for taking the time to answer. Maybe I shouldn't leave feedback
anymore..  like ever.

**Comment by davidnewhall** [comment]
I checked the [hotio template](https://github.com/hotio/unraid-templates/blob/master/hotio/unpackerr.xml) too, and he doesn't use env variables. His template mounts `/config` and uses a config file by default. There's no description at all.

I'm not aware of a third template, so this may just be a case of your eyes playing tricks on you. 

Glad you got it working! Thanks for the report!
