### ISSUE TITLE
Issue with [ERROR] invalid status code, 401 >= 300

### ISSUE THREAD

**Issue by DonMcD** [Unpackerr/unpackerr#398]
I keep getting the error 
[ERROR] 2024/02/21 00:04:32 Radarr (http://10.0.31.4:7878): api.Get(queue): invalid status code, 401 >= 300
[ERROR] 2024/02/21 00:04:32 Sonarr (http://10.0.31.4:8989): api.Get(v3/queue): invalid status code, 401 >= 300

I am able to access my radarr and sonarr servers using the 10.0.31.4 manually but when I try it with unpackerr it gives me errors. Any ideas? I am running everything in docker and followed the guides. Please help

<img width="656" alt="image" src="https://github.com/Unpackerr/unpackerr/assets/90471623/ebda8814-bc11-4902-ae97-4c8368de653f">

**Comment by davidnewhall** [comment]
That means it's the wrong API key.

**Comment by davidnewhall** [comment]
Were you able to figure it out?

**Comment by davidnewhall** [comment]
Let me know if you need more assistance.

**Comment by DonMcD** [comment]
Yup I had the ports mixed up for my radarr and sonarr so the api key would have been screwed up. Thank you
