### ISSUE TITLE
 When `UN_WEBSERVER_METRICS` is enable logs are spammed

### ISSUE THREAD

**Issue by onedr0p** [Unpackerr/unpackerr#399]
My unpackerr logs are being spammed with...

```
10.42.2.97 - - [26/Feb/2024:21:52:25 -0500] "GET /metrics HTTP/1.1" 200 1879 "-" "Prometheus/2.49.1"
```

It would be nice if these could be could be silenced  or sent to a different logging channel (e.g. trace)

**Comment by davidnewhall** [comment]
Set a log file for the web server.
https://github.com/Unpackerr/unpackerr/blob/main/examples/unpackerr.conf.example#L66

**Comment by onedr0p** [comment]
Thanks for the fast reply, can this be /dev/null? 🤣

**Comment by davidnewhall** [comment]
Let me know?

**Comment by onedr0p** [comment]
I had to set it to a file path on disk, but it's a Kubernetes emptyDir so that's fine. Thanks for the quick reply!
