### ISSUE TITLE
[feature request] Option to not preserve timestamps when unpacking

### ISSUE THREAD

**Issue by GinoBadouri** [Unpackerr/unpackerr#401]
Would it be possible to ignore the original timestamps of the files after unpacking?
That way my movies will always be on top in the "recently added" section.

**Comment by davidnewhall** [comment]
What you're proposing as a solution doesn't sound like the correct solution for the problem you briefly described.

**Comment by GinoBadouri** [comment]
yes, but Emby just organises the "recently added" section based on the timestamp of the actual video file (not the folder).
So if I add something like: "The Matrix 1999\The Matrix.mkv" and the "The Matrix 1999.mkv" has a timestamp of let's say 2018, then Emby will put it all the way down in the section as if it was added in 2018.

**Comment by bakerboy448** [comment]
So you want unpackerr to modified the files create date and thus modify what it is extracting to solve an issue that is emby being unable to do basic logic of is this file new to me and when did I see it first?

**Comment by GinoBadouri** [comment]
nevermind, Emby does have the option to use the "scanned date" instead of the file date.
sorry to bother yall

**Comment by davidnewhall** [comment]
Glad you found the correct solution to the problem. Hotio's container works great. Good luck!
