### ISSUE TITLE
Lidarr API key must be filled

### ISSUE THREAD

**Issue by pkp24** [Unpackerr/unpackerr#408]
It says to leave it blank if not using Lidarr but leaving it blank won't let it start in unraid. I filled it with a random set of 32 characters and it started up.

**Comment by pkp24** [comment]
that worked, could it be changed to say delete this url if you aren't using Lidarr?

**Comment by davidnewhall** [comment]
As it's currently written, it's accurate, so there's little haste to make a change. I can add a note to the [unraid doc page](https://unpackerr.zip/docs/install/unraid) though.

**Comment by pkp24** [comment]
the lidarr URL is currently filled in, I had to delete it to get it to work.

**Comment by davidnewhall** [comment]
The Lidarr URL is set to the default value by default. You had to remove your changes to get it to work.

**Comment by pkp24** [comment]
No, I left it as it was with the API key empty and lidar URL filled it and it failed to load because the lidarr api key was wrong. I filled in a fake key and it worked, I deleted the key and the lidarr url and it didn't work.

**Comment by davidnewhall** [comment]
Thanks for the explanation. Found the bug.
