### ISSUE TITLE
Allow specifying API keys and other configuration secrets via `filepath:`

### ISSUE THREAD

**Issue by korfuri** [Unpackerr/unpackerr#410]
Right now the `filepath:` prefix allows keeping the list of archive passwords in a separate file. However the mechanism is not generalized to other sensitive values, i.e. the `api_key` parameters for the various *arrs. This makes it slightly awkward to integrate with secret management systems for these keys.

Would it be possible to generalize the `filepath:` prefix system to all options, or to all potentially-sensitive options instead?

Thanks!

**Comment by davidnewhall** [comment]
Hello @korfuri,

Thank you so much for this feature request. Not only did I add it, I made it a standalone module I can import into any project. It allows me to add this feature to pretty much anything with 3 lines of code. It was a great idea, thanks!

All that said, I've added this feature to Upackerr. It's currently testable in the unstable branch. If you're in docker, use the `:unstable` tag. If you're on another OS, check here: https://unstable.golift.io/unpackerr

Please report back how things work out? 

Thanks!

**Comment by davidnewhall** [comment]
HI @korfuri - still looking for feedback on this!

**Comment by korfuri** [comment]
Hey, thanks for working on this! I haven't had time to try it yet, but I expect I'll have some time this week. Thanks!

**Comment by korfuri** [comment]
I've successfully tested the changes using `filepath:` for the Radarr and Sonarr API keys, I can confirm the changes work and fulfill this feature request. Thanks a lot!
