### ISSUE TITLE
Support for lesser-know .ARJ files

### ISSUE THREAD

**Issue by johnwyles** [Unpackerr/unpackerr#423]
There is a rare occasion I see pop-up where files are compressed using the ARJ file extension and type. Support for extraction of this file type should probably also be included if possible for those instances. Why it's still being used by some I have no idea but it is still kicking around Usenet.

Interesting note about these files that be helpful: When using a Windows machine and extracting these files I (usually) get this warning using 7-zip:
> Warning
> Cannot open the file as [Arj] archive
> The file is open as [Rar5] archive

Sidebar: If it is the case the file extensions are incorrect for ARJ support does Unpackerr try it's magic and run through all options as well? Should that be a feature request? Let me know and I can move this around or reword it however the maintainer(s) see fit.

**Comment by davidnewhall** [comment]
> files are compressed using the ARJ file extension

- Dup: #404 (https://github.com/golift/xtractr/issues/44)

> does Unpackerr try it's magic and run through all options as well

- dup: https://github.com/golift/xtractr/issues/55

Thanks for the arj->rar5 info. Curious if you can rename one to .rar and will unpackerr (or [xt](https://github.com/Unpackerr/xt/releases/tag/v0.0.3)) decompress it? 

Please let me know if you have any questions after reviewing the linked issues, happy to answer them.

**Comment by johnwyles** [comment]
This can be closed (see above).

**Comment by davidnewhall** [comment]
Still curious about that arj file...
