### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by pierrekin** [Unpackerr/unpackerr#471]
Sorry for the hasty issue.

In the settings table here:
https://unpackerr.zip/docs/install/configuration/#global-settings

The `parallel` setting description is not correct.

**Comment by davidnewhall** [comment]
Thanks!

**Comment by davidnewhall** [comment]
It's fixed live now.

This page is all very new (dynamically generated from a yaml def file now). Let me know if you spot anything else weird.
