### ISSUE TITLE
[[Radarr4K]] not accepted as header?

### ISSUE THREAD

**Issue by Kazz3r24** [Unpackerr/unpackerr#474]
I've been using Unpackerr for ages now, and I've always had it set up like this.
[[Sonarr]]
[[Radarr]]
[[Radarr4K]]

I recently discovered that a newer release for unpackerr was available, after updating I noticed that my 4K movies were no longer being extracted. When I looked into it, I noticed that Unpacker only saw 1 Radarr instance and my Sonarr instance. Unpackerr wouldn't recognize my second Radarr instance until I removed the 4K from Radarr. It's working fine now, but why the change? lol I've been running flawlessly up to this point. Now I can only tell which Radarr is which by port number, which isn't ideal with quick glances.

**Comment by bakerboy448** [comment]
[[Radarr4k]] has not and has never been an accepted header

the correct header is [[Radarr]] 

https://unpackerr.zip/docs/install/configuration#two-instances

**Comment by Kazz3r24** [comment]
I'm just saying it was working for me, and now it's not. I guess it was a bug *shrugs*... Like I said, been using this for a while now.

Anyway, cheers.

**Comment by davidnewhall** [comment]
As the author of the software I can say with 100% certainty that has never worked. You're welcome to roll back to an earlier version to test your theory.

> Now I can only tell which Radarr is which by port number,

Tell where? in the config file? Add a comment: `# THIS IS THE RADARR 4k INSTANCE` You can even put it on the same line as `[[radarr]]`:

```
[[radarr]] # THIS IS THE 4k INSTANCE 
 url = "http://4kstuff" 
 api_key = "more stuff"
```

**Comment by Kazz3r24** [comment]
Either way, it doesn't matter.

Yes, I can add a comment to the config to state which is which, but the only place it matters to me is in the log output. Say for instance when I check the status with `service unpackerr status`.

```shell
Jul 30 11:42:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:42:50.107209 radarr.go:118: [Radarr] Updated (http://127.0.0.1:7877): 0 Items Queued, 0 Retrieved
Jul 30 11:42:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:42:50.107249 logs.go:120: [Unpackerr] Queue: 0 waiting, 0 queued, 0 extracting, 0 extracted, 0 imported, 0 failed, 0 deleted
Jul 30 11:42:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:42:50.107270 logs.go:123: [Unpackerr] Totals: 0 retries, 1 finished, 0|0 webhooks, 0|0 cmdhooks, stacks; event:0, hook:0, del:0, up 2 hours 42 mins 14 ms
Jul 30 11:43:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:43:50.103347 logs.go:120: [Unpackerr] Queue: 0 waiting, 0 queued, 0 extracting, 0 extracted, 0 imported, 0 failed, 0 deleted
Jul 30 11:43:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:43:50.103436 logs.go:123: [Unpackerr] Totals: 0 retries, 1 finished, 0|0 webhooks, 0|0 cmdhooks, stacks; event:0, hook:0, del:0, up 2 hours 43 mins 14 ms
Jul 30 11:44:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:44:50.106739 sonarr.go:118: [Sonarr] Updated (http://127.0.0.1:8989): 0 Items Queued, 0 Retrieved
Jul 30 11:44:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:44:50.107373 radarr.go:118: [Radarr] Updated (http://127.0.0.1:7877): 0 Items Queued, 0 Retrieved
Jul 30 11:44:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:44:50.107742 radarr.go:118: [Radarr] Updated (http://127.0.0.1:7878): 0 Items Queued, 0 Retrieved
Jul 30 11:44:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:44:50.107784 logs.go:120: [Unpackerr] Queue: 0 waiting, 0 queued, 0 extracting, 0 extracted, 0 imported, 0 failed, 0 deleted
Jul 30 11:44:50 lyra unpackerr[3699866]: [INFO] 2024/07/30 15:44:50.107803 logs.go:123: [Unpackerr] Totals: 0 retries, 1 finished, 0|0 webhooks, 0|0 cmdhooks, stacks; event:0, hook:0, del:0, up 2 hours 44 mins 14 ms

``` 

Anyway, I only posted because unpackerr was working for all my ARR's, I updated and it suddenly wasn't recognizing my 4K radarr. I figured out the problem and thought I'd post my question here.

Thank you for the help.
