### ISSUE TITLE
Watch Folders not being extracted if Watch Folder names have same first characters

### ISSUE THREAD

**Issue by AncientVamp** [Unpackerr/unpackerr#488]
Having an issue with unpackerr. Running Debian 12, I noticed rar media moved to some of my watched folders are not being extracted even though unpackerr says its being watched. Did a sudo apt upgrade a few weeks ago which looks like unpackerr got updated. My issue, I have multiple path folders being watched and it looks like if my path folder has similar beginning folder name characters it doesn’t work. Example Watch Folder names: AA, AABB, AACC. Only media moved inside Folder: AA gets extracted. The other Watch Folders nothing happens.
[[folder]]
  path = '~/client/AA/'
  extract_path = '~/unpackerr/'
[[folder]]
  path = '~/client/AABB/'
  extract_path = '~/unpackerr/'
[[folder]]
  path = '~/client/AACC/'
  extract_path = '~/unpackerr/'

After looking at my Server logs, before my server update, I had unpackerr v13.1. Rolling back to that version, everything is working now.

**Comment by bakerboy448** [comment]
Without unpackerr's logs there's not much to do here, please provide logs of unpackerr not detecting anything in the folder added or renames after unpackerr is running

**Comment by AncientVamp** [comment]
[unpackerr.log](https://github.com/user-attachments/files/16830619/unpackerr.log)
This log? Like I mentioned above, media put in TD and Watch folder works but not in other Folders names TD* even though in log it shows its being watched. When I roll back to unpackerr v13.1 everything works.

**Comment by davidnewhall** [comment]
Discussed on Discord. This may be a bug I'll keep an eye out for.
