### ISSUE TITLE
.zipx support

### ISSUE THREAD

**Issue by oOStroudyOo** [Unpackerr/unpackerr#489]
Hello,

I've come across .zipx file today.
I'm actually not too familiar with this extension but seems like it's just an alternative version of .zip: https://kb.winzip.com/help/HELP_WHATISZIPX.htm

Is this something you'd be able to get supported please?

Thanks.

**Comment by kidforpm** [comment]
whilst I don't want to undermine your request, all the*.zipx files I have encountered recently are just renamed RAR5 files, which contain a Dune2 screener and a renamed executable (probably a trojan or virus).

I have not ever encountered zipx in scene releases (not sure about the rules but it might even be forbidden) and not having zipx support might protect less tech savvy users.

**Comment by davidnewhall** [comment]
@oOStroudyOo Sure. Share the file so I can make sure it works. I don't have any zipx otherwise.

**Comment by oOStroudyOo** [comment]
Hello @davidnewhall 

I'll be honest, I deleted the file and haven't come across another one since. Happy for this to be closed considering how rare they seem to be and also based on the comments made by @kidforpm

**Comment by Quack6765** [comment]
Yeah I think they are mostly viruses. Just the fact that going back on the page link where the torrent file was downloaded from, shows that they keep getting removed by the moderation team.

**Comment by oOStroudyOo** [comment]
Yeah I've just followed the link for this torrent and I can see that the uploader has been banned.

Scrap this issue please and I'll find a way to auto block .zipx files instead.

**Comment by davidnewhall** [comment]
Sounds good. Thanks for the info @Quack6765. Take care all!
