### ISSUE TITLE
Remove telegram notification url

### ISSUE THREAD

**Issue by BoKKeR** [Unpackerr/unpackerr#493]
Currently this is the telegram notifications look, you get about 4-5 of these on every unpack. 
![image](https://github.com/user-attachments/assets/70d0401e-e505-4201-ad86-640029d9100f)

The problem is the URL in the link and its preview. It takes up over 50% of the space
we could either:
- remove the url
- disable the URL preview

I would like to take this up as a PR also!

**Comment by davidnewhall** [comment]
Contributions are welcome. Happy to review.
