### ISSUE TITLE
Error: Delete original items after successful extraction

### ISSUE THREAD

**Issue by stoneii2000** [Unpackerr/unpackerr#494]
Hello, I've been trying for a few days to understand what I'm doing wrong.

I use the Folders function on my Windows 10  x64 Client.

All my downloaded folders with rar files end up in this folder. 
It is recognized that something new is coming. It is also unpacked, only after successful unpacking the rar files are not deleted.

[INFO] 2024/10/01 11:53:18.112005 files.go:365: Error: Deleting Z:\FTP\Golda.r42: remove Z:\FTP\Golda.r42: The process cannot access access the file because it is being used by another process.

Here is my configuration 
[unpackerr.conf.txt](https://github.com/user-attachments/files/17203207/unpackerr.conf.txt)

Unfortunately I don't see why it doesn't work. 

I thank you for the help

**Comment by davidnewhall** [comment]
Hello,

I've only ever had 1 other user report this error message from NTFS. In that case, Unpackerr was unable to delete the files it extracted. In your case, it can't delete the originals. 

The error indicates the file is open by another process. I'd guess your downloader has 'em open. 

I do not know enough about Windows or NTFS to provide much troubleshooting advice, but if you search that error message you'll find plenty of tips.

Good luck!

**Comment by stoneii2000** [comment]
Hello, thank you for your reply 

I use an FTP Rush and it is no longer active in the folder when downloading. 
Today it was active and I saw that it deleted a few files but there were a few rare files left on the NTFS share.
Maybe it would help if I waited 10 or 20 minutes before deleting
