### ISSUE TITLE
is it possible to unpack iso from inside of rar file?

### ISSUE THREAD

**Issue by wowperfect** [Unpackerr/unpackerr#495]
Hello, this tool seems really nice and it's mostly working for me except for one thing:

I have a rar file with an iso inside of it and it seems that the iso isn't being unpacked even though I have set `UN_FOLDER_EXTRACT_ISOS=true`. is this kind of nested unpacking supported? do I maybe need to watch the output folder?

right now sonarr is happy with an ISO but plex won't play it, so unpackerr doesn't get the notification that the iso inside the rar needs to be unpacked.

here is my docker compose config:

```
 142   │   unpackerr:
 143   │     image: golift/unpackerr
 144   │     container_name: unpackerr
 145   │     volumes:
 146   │       - /mnt/media/downloads:/downloads
 147   │     restart: unless-stopped
 148   │     user: 0:0
 149   │     environment:
 150   │       - PUID=0
 151   │       - PGID=0
 152   │       - TZ=Etc/UTC
 153   │       - UN_FOLDER_EXTRACT_ISOS=true
 154   │       - UN_LOG_FILE=/downloads/unpackerr.log
 155   │       - UN_SONARR_0_URL=http://localhost:8989
 156   │       - UN_SONARR_0_API_KEY=<funnynumbers1>
 157   │       - UN_RADARR_0_URL=http://localhost:7878
 158   │       - UN_RADARR_0_API_KEY=<funnynumbers2>
 159   │       - UN_SONARR_1_URL=http://localhost:8990
 160   │       - UN_SONARR_1_API_KEY=<funnynumbers3>
 161   │       - UN_RADARR_1_URL=http://localhost:7879
 162   │       - UN_RADARR_1_API_KEY=<funnynumbers4>
```

**Comment by davidnewhall** [comment]
Unpackerr is not going to solve this problem. I suggest not downloading ISOs.

**Comment by wowperfect** [comment]
wait @davidnewhall how does the unpack iso's feature work then???

**Comment by davidnewhall** [comment]
It extracts ISO9660 files. What you have is not that.
