### ISSUE TITLE
Unpack Game-Torrents, too?

### ISSUE THREAD

**Issue by HexagonIsTheBestagon** [Unpackerr/unpackerr#504]
Hey,

I've been using this app to unpack my Sonarr and Radarr torrents when required and it's working beautifully. 
I was wondering if there was a possibility to have it watch a folder where Qbittorrent is placing my downloaded games right now, and then unpack those so that I just have to copy them over to my main system. 

I had a look at the "Watch Folder" section in the docs, but I didn't quite understand if that would interfere with my existing automation for Sonarr and Radarr.

**Comment by davidnewhall** [comment]
Try it out.

**Comment by HexagonIsTheBestagon** [comment]
`      # Folder Watch Config for Games
      - UN_FOLDER_0_PATH=/downloads/Games
      - UN_FOLDER_0_EXTRACT_PATH=/downloads/Games/Unpacked
      - UN_FOLDER_0_DELETE_AFTER=0
      - UN_FOLDER_0_EXTRACT_ISOS=true`
      
    I've included the solution above. It's straightforward, to be honest.

**Comment by davidnewhall** [comment]
You probably don't want to extract ISOs. Maybe, but really depends what they are. Your settings seem good. If you find it extracts things before the download finishes, please re-open and post the log file.
