### ISSUE TITLE
Readarr connection broken

### ISSUE THREAD

**Issue by Artalius** [Unpackerr/unpackerr#505]
Docker composed, standalone

Unable to connect to Readarr 
_Package Version 0.4.4.2686-ls131 by [linuxserver.io](https://www.linuxserver.io/)_

`
[ERROR] 2024/11/28 21:48:49 Readarr (http://192.168.y.x:8787): api.Get(v1/queue): httpClient.Do(req): Get "http://192.168.y.x:8787/api/v1/queue?includeUnknownAuthorItems=true&page=1&pageSize=2000&sortDirection=ascending&sortKey=timeleft": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`

The exact URL and API key are matched as defined, and working in Postman GET, if the API-key key is defined as `X-Api-Key` and added to header.

**Comment by davidnewhall** [comment]
Unpackerr can't connect to `192.168.y.x` on port 8787. Either wrong IP, wrong port, or the network is unreachable from unpacker's location. Did you have any questions?

**Comment by Artalius** [comment]
In addition, curl also works at that port an IP from the Docker host.

The POSTMAN, Curl, and web browser can access Readarr from various points on LAN.

UnPackerr can access 3 other services properly.

**Comment by davidnewhall** [comment]
The error messages indicates a lack of network route from unpackerr to that IP, or you've set the timeout to 0. Not really any other in-betweens.

**Comment by Artalius** [comment]
[unpackerr_cleaned.log](https://github.com/user-attachments/files/17954012/unpackerr_cleaned.log)

Log from last boot, and removed IP and faff working logs.

**Comment by davidnewhall** [comment]
How long does postman take to pull a result from this url? ```http://192.168.y.x:8787/api/v1/queue?includeUnknownAuthorItems=true&page=1&pageSize=2000&sortDirection=ascending&sortKey=timeleft```
How large is the result?

**Comment by Artalius** [comment]
![image](https://github.com/user-attachments/assets/811d4c8c-f1a2-4f87-b4e8-ac6c953ab26a)

**Comment by davidnewhall** [comment]
Strange. If x and y are the same variables throughout the log, then you have a gremlin I can't explain. Perhaps try drastic things like reboot, recreate the container, try another image (hotio vs golift), etc. Try increasing the timeout, just in case.
