### ISSUE TITLE
Zipx ? Support ?

### ISSUE THREAD

**Issue by Arawac22** [Unpackerr/unpackerr#508]
Hi,

Would it be possible to add zipx support, I suddenly had a couple of them and would be nice is yours could auto unpack.

**Comment by davidnewhall** [comment]
They're probably viruses.  No one has given me a good reason why these files need to be extracted.

- #489 
- #507

**Comment by davidnewhall** [comment]
If you found one that's not a virus, please share it and let us know where it came from.

**Comment by Arawac22** [comment]
Oh good thanks didn't know that !

**Comment by alphasierracharly** [comment]
torrentleech.org has a lot of zipx files

**Comment by davidnewhall** [comment]
![Screenshot 2024-12-09 at 1 33 03 PM](https://github.com/user-attachments/assets/0b5e1c29-9503-459d-9764-211a6c75125a)
Going to need more info if you're asking for zip support.

**Comment by alphasierracharly** [comment]
Shoot, I was mistaken by the source. Yes it was from open tracker Limetorrents. Clearly less reliable. 

example: https://www.limetorrents.lol/Gladiator-II-2024-HD-c1nem4-x264-SUNSCREEN[TGx]-torrent-18699219.html
However, I take my vote on this request back

**Comment by davidnewhall** [comment]
Looks like a virus.
