### ISSUE TITLE
Extend Sync Support beyond SyncThing

### ISSUE THREAD

**Issue by SteveGilvarry** [Unpackerr/unpackerr#509]
Feature Request. I use LFTP for sync via https://github.com/weaselBuddha/Queue4Download, and get errors when the extract tries at triggering point, I am playing with start delay and retry etc. But I had a quick look at syncthing code and saw it is just looking for .tmp files and could work for lftp transfers which are just .lftp-pget-status. Could either just check for both under a check for sync files feature or allow file type to be variable?
Happy to have a go at the change over next few weeks if you like, or test if you have time to make it.

**Comment by davidnewhall** [comment]
> Happy to have a go at the change over next few weeks if you like, or test if you have time to make it.

Happy to review your code and/or provide pointers. Jump on discord if you want to chat about it.

**Comment by SteveGilvarry** [comment]
I ended up solving this via lftp config as Radarr and Sonarr were also getting trigger happy on files before they had written in full. Opted to use a temp file name during the transfer and made it the same as syncthing so your existing check for *.tmp would work.
Added to ~/.ltfp/rc
`set xfer:temp-file-name *.tmp`
`set xfer:use-temp-file yes`

**Comment by davidnewhall** [comment]
bad ass. Thanks for sharing!
